services:
  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/toruj/frontend:latest}
    env_file:
      - ./frontend/.env.production
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    networks:
      - mars-network
    depends_on:
      - backend

  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/toruj/backend:latest}
    env_file:
      - ./backend/.env.production
    environment:
      # Override NODE_ENV if needed
      - NODE_ENV=production
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - mars-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-production.conf:/etc/nginx/nginx.conf:ro
      # Add SSL certificates if needed
      # - ./ssl:/etc/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - mars-network

networks:
  mars-network:
    driver: bridge
