services:
  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/toruj/frontend:latest}
    env_file:
      - ./frontend/.env.development
    environment:
      - NODE_ENV=development
    networks:
      - mars-network
    depends_on:
      - backend

  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/toruj/backend:latest}
    env_file:
      - ./backend/.env.development
    environment:
      # Override NODE_ENV if needed
      - NODE_ENV=development
    volumes:
      - mars_upload_data:/app/uploads
    restart: unless-stopped
    networks:
      - mars-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/jirawuth/docker-configs/nginx/nginx-development.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - mars-network

networks:
  mars-network:
    driver: bridge

volumes:
  mars_upload_data:
    driver: local