import React, { createContext, useContext, useEffect, useState, useCallback, type ReactNode } from 'react';

export type Language = 'en' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation keys
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.apply': 'Apply',
    'common.reset': 'Reset',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.warning': 'Warning',
    'common.search': 'Search',
    'common.hideFilters': 'Hide Filters',
    'common.showFilters': 'Show Filters',
    'common.clear': 'Clear',
    'common.close': 'Close',
    'common.retry': 'Retry',
    'common.seeMore': 'See More',
    'common.showLess': 'Show Less',
    'common.more': 'more',
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.tickets': 'Tickets',
    'nav.machines': 'Machines',
    'nav.reports': 'Reports',
    'nav.users': 'Users',
    'nav.settings': 'Settings',
    
    // Authentication
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.register': 'Register',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.email': 'Email',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.employeeID': 'Employee ID',
    'auth.department': 'Department',
    'auth.shift': 'Shift',
    'auth.currentPassword': 'Current Password',
    'auth.newPassword': 'New Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.changePassword': 'Change Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.rememberMe': 'Remember Me',
    'auth.loginSuccess': 'Login successful',
    'auth.logoutSuccess': 'Logout successful',
    'auth.registrationSuccess': 'Registration successful',
    'auth.passwordChangeSuccess': 'Password changed successfully',
    
    // User roles
    'role.l1_operator': 'L1 Operator',
    'role.l2_engineer': 'L2 Engineer',
    'role.l3_manager': 'L3 Manager',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.plant': 'Plant',
    'dashboard.allPlants': 'All Plants',
    'dashboard.unsavedChanges': 'You have unsaved changes',
    'dashboard.reset': 'Reset',
    'dashboard.applyFilters': 'Apply Filters',
    'dashboard.pleaseCheckYourConnectionAndTryAgain': 'Please check your connection and try again. If the problem persists, contact your system administrator.',
    // Profile
    'profile.title': 'User Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.workInfo': 'Work Information',
    'profile.lastLogin': 'Last Login',
    'profile.memberSince': 'Member Since',
    'profile.profileInformation': 'Profile Information',
    'profile.changeProfilePicture': 'Change Profile Picture',
    'profile.upload': 'Upload',
    'profile.chooseFile': 'Choose File',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.jobTitle': 'Title',
    'profile.department': 'Department',
    'profile.selectDepartment': 'Select Department',
    'profile.noDepartment': 'No Department',
    'profile.group': 'Group',
    'profile.personCode': 'Person Code',
    'profile.personCodePlaceholder': 'Employee code (max 20 characters)',
    'profile.personCodeTooLong': 'Person code must be 20 characters or less',
    'profile.saveChanges': 'Save Changes',
    'profile.profileUpdated': 'Profile updated',
    'profile.failedToUpdateProfile': 'Failed to update profile',
    'profile.avatarUpdated': 'Avatar updated',
    'profile.failedToUploadAvatar': 'Failed to upload avatar',
    'profile.avatarUploadHint': 'Select an image, crop it, and it will be uploaded automatically.',
    'profile.applyAndUpload': 'Apply & Upload',
    'profile.uploading': 'Uploading...',
    'profile.invalidImageFile': 'Please select a valid image file',
    'profile.imageTooLarge': 'Image file is too large (max 10MB)',
    'profile.failedToLoadImage': 'Failed to load image',
    'profile.lineNotifications': 'LINE Notifications',
    'profile.lineUserId': 'LINE User ID (for notifications)',
    'profile.enterLineId': 'Enter your LineID',
    'profile.sendTestLineNotification': 'Send Test LINE Notification',
    'profile.ensureLineIdSet': 'Ensure your LineID is set above.',
    'profile.testNotificationSent': 'Test notification sent to your LINE.',
    'profile.failedToSendTestNotification': 'Failed to send test notification',
    'profile.pleaseEnterLineId': 'Please enter a LINE ID to test',
    'profile.lineIdChangedNotSaved': 'Your LINE ID has been changed but not saved yet. Click "Save LINE ID" to save it permanently.',
    'profile.testWillUseCurrentInput': 'Test will use the LINE ID you entered above.',
    'profile.testWillUseSavedLineId': 'Test will use your saved LINE ID.',
    'profile.saveLineId': 'Save LINE ID',
    'profile.saving': 'Saving...',
    'profile.lineIdUpdated': 'LINE ID updated successfully',
    'profile.failedToUpdateLineId': 'Failed to update LINE ID',
    'profile.note': 'Note',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.passwordChanged': 'Password changed',
    'profile.failedToChangePassword': 'Failed to change password',
    'profile.lineHelpTitle': 'How to get your LINE User ID',
    'profile.lineHelpDescription': 'Follow these steps to get your LINE User ID for notifications:',
    'profile.step1Title': 'Add our LINE Official Account',
    'profile.step1Description': 'Scan the QR code below or click the link to add our LINE account as a friend.',
    'profile.addLineFriend': 'Add LINE Friend',
    'profile.step2Title': 'Send "Line ID" message',
    'profile.step2Description': 'Open the chat with our LINE account and send the message:',
    'profile.step3Title': 'Copy your User ID',
    'profile.step3Description': 'Copy the returned User ID and paste it in the field above.',
    'profile.gotIt': 'Got it!',
    'profile.cropAvatar': 'Crop Avatar',
    'profile.zoom': 'Zoom',
    'profile.cancel': 'Cancel',
    'profile.apply': 'Apply',
    'profile.failedToCropImage': 'Failed to crop image',
    'profile.lineAccount': 'LINE Account',
    'profile.linkedLineAccount': 'Linked LINE Account',
    'profile.lineDisplayName': 'LINE Display Name',
    'profile.lineProfilePicture': 'LINE Profile Picture',
    'profile.unlinkLineAccount': 'Unlink LINE Account',
    'profile.unlinkConfirmationTitle': 'Unlink LINE Account',
    'profile.unlinkConfirmationMessage': 'Are you sure you want to unlink your LINE account? You will no longer receive LINE notifications.',
    'profile.unlinkSuccess': 'LINE account unlinked successfully',
    'profile.unlinkFailed': 'Failed to unlink LINE account',
    'profile.logoutInstructionTitle': 'Account Unlinked',
    'profile.logoutInstructionMessage': 'Your LINE account has been unlinked. Please logout and login again to link a new LINE account.',
    'profile.logoutNow': 'Logout Now',
    'profile.lineAccountNotLinked': 'No LINE account linked',
    'profile.failedToGetLineProfile': 'Failed to get LINE profile information',
    'profile.unsavedChanges': 'Unsaved changes',
    
    // Settings
    'settings.title': 'Settings',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    
    // Theme
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.auto': 'Auto',
    
    // Language
    'language.english': 'English',
    'language.thai': 'ไทย',
    
    // Errors
    'error.invalidCredentials': 'Invalid username or password',
    'error.userNotFound': 'User not found',
    'error.unauthorized': 'Unauthorized access',
    'error.forbidden': 'Access forbidden',
    'error.notFound': 'Page not found',
    'error.serverError': 'Internal server error',
    'error.networkError': 'Network error',
    'error.validationError': 'Validation error',
    
    // Validation
    'validation.required': 'This field is required',
    'validation.email': 'Please enter a valid email address',
    'validation.passwordLength': 'Password must be at least 6 characters long',
    'validation.passwordMatch': 'Passwords do not match',
    'validation.usernameLength': 'Username must be at least 3 characters long',
    
    // Homepage specific
    'homepage.welcome': 'Welcome back',
    'homepage.quickActions': 'Quick Actions',
    'homepage.tasks': 'Tasks',
    'homepage.performance': 'Performance',
    'homepage.pendingTickets': 'Pending Tickets',
    'homepage.personal': 'Personal',
    'homepage.team': 'Team',
    'homepage.createTicket': 'Create Ticket',
    'homepage.viewTickets': 'View Tickets',
    'homepage.reportNewIssue': 'Report a new issue or request',
    'homepage.checkTicketStatus': 'Check your ticket status',
    'homepage.loadingPendingTickets': 'Loading pending tickets...',
    'homepage.errorLoadingTickets': 'Error loading tickets',
    'homepage.noPendingTickets': 'No pending tickets',
    'homepage.allTicketsUpToDate': 'All your tickets are up to date!',
    'homepage.youCreatedThisTicket': 'You created this ticket',
    'homepage.requiresYourApproval': 'Requires your approval',
    'homepage.viewOnly': 'View only',
    'homepage.myFinishCasesPerPeriod': 'My Finish Cases Per Period',
    'homepage.myReportCasePerPeriod': 'My Report Case Per Period',
    'homepage.setupKPI': 'Setup KPI',
    'homepage.errorLoadingChartData': 'Error loading chart data',
    'homepage.noFinishedTicketData': 'No Finished ticket data available',
    'homepage.finishSomeTickets': 'Finish some tickets to see your performance!',
    'homepage.noTicketDataAvailable': 'No ticket data available',
    'homepage.startCreatingTickets': 'Start creating tickets to see your performance!',
    'homepage.asReporter': 'As Reporter (How I Help by Reporting)',
    'homepage.asActionPerson': 'As Action Person (How I Help by Fixing)',
    'homepage.errorLoadingKPIData': 'Error loading KPI data',
    'homepage.loadingPersonalMetrics': 'Loading personal metrics...',
    'homepage.noKPIDataAvailable': 'No KPI data available',
    'homepage.myReportsCreated': 'My Reports Created',
    'homepage.downtimeAvoidedByMyReports': 'Downtime Avoided by My Reports',
    'homepage.costAvoidedByMyReports': 'Cost Avoided by My Reports',
    'homepage.casesIFixed': 'Cases I Fixed',
    'homepage.downtimeIFixed': 'Downtime I Fixed',
    'homepage.costIFixed': 'Cost I Fixed',
    'homepage.noChange': 'No change',
    'homepage.teamPerformance': 'Team Performance',
    'homepage.teamPerformanceComingSoon': 'Team performance metrics coming soon...',
    'homepage.filters': 'Filters',
    'homepage.range': 'Range',
    'homepage.currentSelection': 'Current Selection',
    'homepage.thisYear': 'This Year',
    'homepage.lastYear': 'Last Year',
    'homepage.thisPeriod': 'This Period',
    'homepage.FinishedTickets': 'Finished Tickets',
    'homepage.target': 'Target',
    'homepage.myTickets': 'My Tickets',
    'homepage.failedToFetchPendingTickets': 'Failed to fetch pending tickets',
    'homepage.failedToFetchPersonalTicketData': 'Failed to fetch personal ticket data',
    'homepage.failedToFetchPersonalFinishedTicketData': 'Failed to fetch personal Finished ticket data',
    'homepage.failedToFetchPersonalKPIData': 'Failed to fetch personal KPI data',
    // Relationship-based ticket section titles
    'homepage.escalatedTickets': 'Escalated Tickets',
    'homepage.ticketsToAccept': 'Tickets to be Accepted by Owner',
    'homepage.ticketsToClose': 'Tickets to be Approved and Closed by Manager',
    'homepage.ticketsToReview': 'Tickets to be Reviewed by Reporter',
    'homepage.ticketsToReviewRejected': 'Tickets to be Reviewed (Rejected)',
    'homepage.ticketsToPlan': 'Tickets to Plan',
    'homepage.myAssignedTickets': 'My Assigned Tickets',
    'homepage.myCreatedTickets': 'My Created Tickets',
    'homepage.otherTickets': 'Other Tickets',
    // Mobile card labels
    'homepage.accepted': 'Accepted',
    'homepage.acceptedBy': 'Accepted by',
    'homepage.escalated': 'Escalated',
    'homepage.escalatedBy': 'Escalated by',
    'homepage.reviewed': 'Reviewed',
    'homepage.reviewedBy': 'Reviewed by',
    'homepage.finished': 'Finished',
    'homepage.finishedBy': 'Finished by',
    'homepage.rejected': 'Rejected',
    'homepage.rejectedBy': 'Rejected by',
    'homepage.scheduledStart': 'Scheduled start',
    'homepage.scheduledFinish': 'Scheduled finish',
    'homepage.createdBy': 'Created by',
    'homepage.created': 'Created',
    'homepage.assignedTo': 'Assigned to',
    
    // Personal KPI Modal
    'personalKPI.title': 'Personal KPI Target Setup',
    'personalKPI.reportCases': 'Report Cases',
    'personalKPI.fixCases': 'Fix Cases',
    'personalKPI.error': 'Error',
    'personalKPI.success': 'Success',
    'personalKPI.validationError': 'Validation Error',
    'personalKPI.failedToFetchExistingTargets': 'Failed to fetch existing targets',
    'personalKPI.userInformationNotAvailable': 'User information not available',
    'personalKPI.failedToSavePersonalTargets': 'Failed to save personal targets',
    'personalKPI.user': 'User',
    'personalKPI.personNo': 'Person No',
    'personalKPI.year': 'Year',
    'personalKPI.unit': 'Unit',
    'personalKPI.case': 'Case',
    'personalKPI.thb': 'THB',
    'personalKPI.percent': 'Percent',
    'personalKPI.existingTargetsWarning': 'You already have targets set for {type} in {year}. Saving new values will replace the existing targets.',
    'personalKPI.periodValues': 'Period Values',
    'personalKPI.copyP1ToAll': 'Copy P1 to All',
    'personalKPI.resetForm': 'Reset Form',
    'personalKPI.cancel': 'Cancel',
    'personalKPI.saveTargets': 'Save Targets',
    'personalKPI.saving': 'Saving...',
    'personalKPI.fillAllPeriods': 'Please fill in values for all periods: {periods}',
    'personalKPI.targetsSavedSuccess': 'Personal targets saved successfully for {type} in {year}',
    'personalKPI.report': 'Report',
    'personalKPI.fix': 'Fix',
    'personalFilter.title': 'Personal Performance Filters',
    'personalFilter.timeRange': 'Time Range',
    'personalFilter.selectTimeRange': 'Select time range',
    'personalFilter.thisYear': 'This Year',
    'personalFilter.lastYear': 'Last Year',
    'personalFilter.thisPeriod': 'This Period',
    'personalFilter.selectPeriod': 'Select Period',
    'personalFilter.year': 'Year',
    'personalFilter.period': 'Period',
    'personalFilter.applyFilters': 'Apply Filters',
    'personalFilter.unsavedChanges': 'Unsaved changes',
    
    // Common chart labels
    'chart.FinishedTickets': 'Finished Tickets',
    'chart.target': 'Target',
    'chart.myTickets': 'My Tickets',
    
    // Ticket Management
    'ticket.create': 'Create Ticket',
    'ticket.edit': 'Edit Ticket',
    'ticket.view': 'View Ticket',
    'ticket.title': 'Title',
    'ticket.description': 'Description',
    'ticket.status': 'Status',
    'ticket.priority': 'Priority',
    'ticket.severity': 'Severity',
    'ticket.pucode': 'PUCODE',
    'ticket.area': 'Area',
    'ticket.created': 'Created',
    'ticket.updated': 'Updated',
    'ticket.assignee': 'Assignee',
    'ticket.assignedTo': 'Assigned To',
    'ticket.reporter': 'Reporter',
    'ticket.reportAbnormalFinding': 'Report Abnormal Finding',
    'ticket.briefDescription': 'Brief description of the abnormal finding',
    'ticket.detailedDescription': 'Detailed description of the abnormal finding, including symptoms and observations',
    'ticket.titleRequired': 'Title is required',
    'ticket.descriptionRequired': 'Description is required',
    'ticket.pucodeRequired': 'PUCODE is required',
    'ticket.machineName': 'Machine Name', // Added machine name
    'ticket.ticketCreatedSuccess': 'Ticket created successfully',
    'ticket.ticketUpdatedSuccess': 'Ticket updated successfully',
    'ticket.failedToCreateTicket': 'Failed to create ticket',
    'ticket.failedToUpdateTicket': 'Failed to update ticket',
    'ticket.failedToFetchTickets': 'Failed to fetch tickets',
    'ticket.noTicketsFound': 'No tickets found',
    'ticket.loadingTickets': 'Loading tickets...',
    'ticket.errorLoadingTickets': 'Error loading tickets',
    'ticket.searchTickets': 'Search tickets...',
    'ticket.filterByStatus': 'Filter by status',
    'ticket.filterByPriority': 'Filter by priority',
    'ticket.filterBySeverity': 'Filter by severity',
    'ticket.allStatuses': 'All Statuses',
    'ticket.allPriorities': 'All Priorities',
    'ticket.allSeverities': 'All Severities',
    'ticket.allAreas': 'All Areas',
    'ticket.allUsers': 'All Users',
    'ticket.searchUsers': 'Search users...',
    'ticket.open': 'Open',
    'ticket.assigned': 'Assigned',
    'ticket.inProgress': 'In Progress',
    'ticket.pending': 'Pending',
    'ticket.resolved': 'Resolved',
    'ticket.reviewed': 'Reviewed',
    'ticket.closed': 'Closed',
    'ticket.cancelled': 'Cancelled',
    'ticket.rejectedPendingL3Review': 'Rejected (Pending Planner Review)',
    'ticket.rejectedFinal': 'Rejected (Final)',
    
    // Critical levels
    'ticket.critical': 'Critical',
    'ticket.criticalLevel1': 'No Information',
    'ticket.criticalLevel2': 'No Information',
    'ticket.criticalLevel3': 'No Information',
    'ticket.criticalLevel4': 'No Information',
    'ticket.criticalLevel5': 'Production Stop',
    'ticket.criticalLevel6': 'Production Dropped',
    'ticket.criticalLevel7': 'No Impact',
    'ticket.allCriticalLevels': 'All Critical Levels',
    'ticket.finished': 'Finished',
    'ticket.escalated': 'Escalated',
    'ticket.reopenedInProgress': 'Reopened',
    'ticket.low': 'Low',
    'ticket.medium': 'Medium',
    'ticket.high': 'High',
    'ticket.normal': 'Normal',
    'ticket.urgent': 'Urgent',
    'ticket.costAvoidance': 'Cost Avoidance',
    'ticket.downtimeAvoidance': 'Downtime Avoidance (Hours)',
    'ticket.failureMode': 'Failure Mode',
    'ticket.attachments': 'Attachments',
    'ticket.addAttachment': 'Add Attachment',
    'ticket.removeAttachment': 'Remove Attachment',
    'ticket.comments': 'Comments',
    'ticket.addComment': 'Add Comment',
    'ticket.noComments': 'No comments yet',
    'ticket.history': 'History',
    'ticket.timeline': 'Timeline',
    'ticket.actions': 'Actions',
    'ticket.approve': 'Approve',
    'ticket.reject': 'Reject',
    'ticket.assign': 'Assign',
    'ticket.unassign': 'Unassign',
    'ticket.approveReview': 'Approve Review',
    'ticket.reviewReason': 'Review Reason',
    'ticket.approveClose': 'Approve Close',
    'ticket.close': 'Close',
    'ticket.reopen': 'Reopen',
    'ticket.scheduleStart': 'Schedule Start',
    'ticket.scheduleFinish': 'Schedule Finish',
    'ticket.assignTo': 'Assign To',
    'ticket.pleaseSelectAssignee': 'Please select assignee',
    'ticket.plan': 'Plan',
    'ticket.start': 'Start',
    'ticket.actualStartTime': 'Actual Start Time',
    'ticket.actualStartTimeHelp': 'Default is current time, but you can adjust if needed',
    'ticket.actualStartTimeEditHelp': 'Edit the actual start time if different from when work was started',
    'ticket.actualFinishTime': 'Actual Finish Time',
    'ticket.actualFinishTimeHelp': 'When the work was actually completed',
    'ticket.duplicate': 'Duplicate',
    'ticket.duplicateTicket': 'Duplicate Ticket',
    'ticket.originalTicket': 'Original Ticket',
    'ticket.relatedTickets': 'Related Tickets',
    'ticket.dependencies': 'Dependencies',
    'ticket.tags': 'Tags',
    'ticket.addTag': 'Add Tag',
    'ticket.removeTag': 'Remove Tag',
    'ticket.wizard': 'Ticket Creation Wizard',
    'ticket.wizardStep1': 'Step 1: Basic Information',
    'ticket.wizardStep2': 'Step 2: Details',
    'ticket.wizardStep3': 'Step 3: Review',
    'ticket.wizardNext': 'Next',
    'ticket.wizardPrevious': 'Previous',
    'ticket.wizardFinish': 'Finish',
    'ticket.wizardCancel': 'Cancel',
    'ticket.wizardBack': 'Back',
    'ticket.wizardReview': 'Review',
    'ticket.wizardConfirm': 'Confirm',
    'ticket.wizardSuccess': 'Ticket created successfully!',
    'ticket.wizardError': 'Error creating ticket',
    'ticket.wizardValidationError': 'Please fill in all required fields',
    'ticket.wizardSelectPlant': 'Select Plant',
    'ticket.wizardSelectArea': 'Select Area',
    'ticket.wizardSelectLine': 'Select Line',
    'ticket.wizardSelectMachine': 'Select Production Unit',
    'ticket.wizardSelectPUCODE': 'Select PUCODE',
    'ticket.wizardSelectFailureMode': 'Select Failure Mode',
    'ticket.wizardUploadImages': 'Upload Images',
    'ticket.wizardDragDropImages': 'Drag and drop images here, or click to select',
    'ticket.wizardImagePreview': 'Image Preview',
    'ticket.wizardRemoveImage': 'Remove Image',
    'ticket.wizardMaxImages': 'Maximum 5 images allowed',
    'ticket.wizardImageSize': 'Image size should be less than 5MB',
    'ticket.wizardImageFormat': 'Only JPG, PNG, GIF formats are allowed',
    'ticket.deleteConfirm': 'Are you sure you want to delete this ticket?',
    
    // Hierarchical selection
    'ticket.selectionModeSearch': 'Search',
    'ticket.selectionModeHierarchy': 'Browse Hierarchy',
    'ticket.selectPlant': 'Select Plant',
    'ticket.selectArea': 'Select Area',
    'ticket.selectLine': 'Select Line',
    'ticket.selectMachine': 'Select Production Unit',
    'ticket.selectNumber': 'Select Number',
    'ticket.hierarchyPathSelected': 'Selected Path',
    'ticket.hierarchyHelpText': 'Navigate through the hierarchy to find your production unit. You can select at any level - Plant, Area, Line, or Machine.',
    'ticket.selectLineOrMachine': 'Select Line or Machine',
    'ticket.lineOption': 'Line: {name}',
    'ticket.machineOption': 'Machine: {name}',
    'ticket.noneOption': 'None (No Line)',
    'ticket.ticketDeletedSuccess': 'Ticket deleted successfully',
    'ticket.failedToDeleteTicket': 'Failed to delete ticket',
    'ticket.delete': 'Delete',
    'ticket.deleteTicket': 'Delete Ticket',
    'ticket.deleteReason': 'Deletion Reason',
    'ticket.deleteReasonPlaceholder': 'Please provide a reason for deleting this ticket...',
    'ticket.deleteReasonRequired': 'Deletion reason is required',
    'ticket.deleteWarning': 'This action cannot be undone. The ticket will be permanently deleted.',
    'ticket.deleting': 'Deleting...',
    'ticket.confirmDelete': 'Confirm Delete',
    'ticket.warning': 'Warning',
    'ticket.fileSkipped': 'Some files were skipped. Only image files are supported.',
    'ticket.fileSizeExceeded': 'file(s) were skipped. Maximum file size is 10MB.',
    'ticket.searchMachines': 'Searching...',
    'ticket.failedToSearchPU': 'Failed to search production unit. Please try again.',
    'ticket.atLeastOneAttachment': 'At least one attachment is required',
    'ticket.selectedPU': 'Selected Production Unit',
    'ticket.typeToSearch': 'Type at least 2 characters to search from PU or PUCODE',
    'ticket.attachImages': 'Attach Problem Images',
    'ticket.dragDropFiles': 'Drag & drop files here or',
    'ticket.dropFilesHere': 'Drop files here',
    'ticket.browseFiles': 'Browse files',
    'ticket.imageUploadInfo': 'PNG, JPG, or JPEG up to 10MB each. Images upload after ticket creation.',
    'ticket.selectedFiles': 'Selected:',
    'ticket.clearAll': 'Clear all',
    'ticket.remove': 'Remove',
    'ticket.problemTitle': 'Problem Title',
    'ticket.addConciseTitle': 'Add a concise problem title',
    'ticket.describeAbnormalFinding': 'Describe the abnormal finding in detail',
    'ticket.selectSeverity': 'Select severity',
    'ticket.selectPriority': 'Select priority',
    'ticket.submitReport': 'Submit Report',
    'ticket.creating': 'Creating…',
    'ticket.uploadingImages': 'Uploading images…',
    'ticket.ticketNumber': 'Ticket #',
    'ticket.createdBy': 'Created By',
    'ticket.unassigned': 'Unassigned',
    'ticket.to': 'to',
    'ticket.of': 'of',
    'ticket.export': 'Export',
    'ticket.exportComingSoon': 'Export (coming soon)',
    'ticket.exportTickets': 'Export tickets to CSV',
    'ticket.noTicketsToExport': 'No tickets to export',
    'ticket.exportSuccess': 'Tickets exported successfully',
    'ticket.ticketNotFound': 'Ticket Not Found',
    'ticket.ticketNotFoundDescription': 'The requested ticket could not be found.',
    'ticket.backToTickets': 'Back to Tickets',
    'ticket.accept': 'Accept',
    'ticket.overrideAccept': 'Override & Accept',
    'ticket.finalReject': 'Final Reject',
    'ticket.finish': 'Finish',
    'ticket.escalate': 'Escalate',
    'ticket.reassign': 'Reassign',
    'ticket.imageEvidence': 'Image Evidence',
    'ticket.before': 'Before',
    'ticket.after': 'After',
    'ticket.photo': 'photo',
    'ticket.photos': 'photos',
    'ticket.noBeforeImages': 'No before images uploaded yet.',
    'ticket.noAfterImages': 'No after images uploaded yet.',
    'ticket.addProblemEvidence': 'Add problem evidence',
    'ticket.shareImprovementResults': 'Share improvement results',
    'ticket.dragDropOrChoose': 'Drag & drop or choose files to upload.',
    'ticket.uploading': 'Uploading...',
    'ticket.upload': 'Upload',
    'ticket.image': 'image',
    'ticket.images': 'images',
    'ticket.uploadDisabled': 'Upload disabled for closed or rejected tickets.',
    'ticket.afterGalleryUnlock': 'After gallery will unlock once this ticket is accepted or moves to in-progress.',
    'ticket.commentPlaceholder': 'Share an update or ask a question...',
    'ticket.failedToAddComment': 'Failed to add comment',
    'ticket.postComment': 'Post Comment',
    'ticket.ticketInformation': 'Ticket Information',
    'ticket.location': 'Location',
    'ticket.scheduledStartdate': 'Scheduled Start Date',
    'ticket.scheduledFinishdate': 'Scheduled Finish Date',
    'ticket.actualStartdate': 'Actual Start Date',
    'ticket.actualFinishdate': 'Actual Finish Date',
    'ticket.noLocationDetails': 'No location details recorded.',
    'ticket.hours': 'hours',
    'ticket.workflowTimeline': 'Workflow Timeline',
    'ticket.ticketCreated': 'Ticket Created',
    'ticket.by': 'by',
    'ticket.ticketAssigned': 'Ticket Assigned',
    'ticket.statusChangedTo': 'Status Changed to',
    'ticket.rejectionReason': 'Rejection Reason *',
    'ticket.closeReason': 'Close Reason',
    'ticket.reopenReason': 'Reopen Reason',
    'ticket.notes': 'Notes',
    'ticket.rejectionReasonRequired': 'Rejection reason is required',
    'ticket.scheduledFinishedate': 'Scheduled Finish Date',
    'ticket.scheduledFinishedateRequired': 'Scheduled completion date is required',
    'ticket.downtimeAvoidanceHours': 'Downtime Avoidance (hours)',
    'ticket.costAvoidanceTHB': 'Cost Avoidance (THB)',
    'ticket.selectFailureMode': 'Select failure mode',
    'ticket.satisfactionRating': 'Satisfaction Rating',
    'ticket.newAssignee': 'New Assignee *',
    'ticket.searchL2L3User': 'Search Maintenance/Planner by name/email',
    'ticket.searching': 'Searching...',
    'ticket.noUsersFound': 'No users found',
    'ticket.pleaseSelectNewAssignee': 'Please select a new assignee',
    'ticket.selectedUserId': 'Selected user ID',
    'ticket.escalateToL3User': 'Escalate To Planner',
    'ticket.searchL3User': 'Search Planner by name/email',
    'ticket.noL3UsersFound': 'No Planners found',
    'ticket.selectedL3UserId': 'Selected Planner ID',
    'ticket.finalRejectionMessage': 'This will be a final rejection.',
    'ticket.rejectionL3ReviewMessage': 'This rejection will be sent to Planner for review.',
    'ticket.working': 'Working...',
    'ticket.chooseFiles': 'Choose Files',
    'ticket.showing': 'Showing',
    'ticket.criticalLevel': 'Critical Level',
    'ticket.ticketClass': 'Ticket Class (Optional)',
    'ticketManagement.title': 'Abnormal Finding Report',
    'ticketManagement.createTicket': 'Create Ticket',
    'ticket.atLeastOneAfterImageRequired': 'At least one "after" image is required',

    // Dashboard specific
    'dashboard.abnormalReport': 'Abnormal Report Dashboard',
    'dashboard.totalTickets': 'Total Tickets',
    'dashboard.closedTickets': 'Closed Tickets',
    'dashboard.waitingTickets': 'Waiting Tickets',
    'dashboard.pendingTickets': 'Pending Tickets',
    'dashboard.totalDowntimeAvoidance': 'Total Downtime Avoidance',
    'dashboard.totalCostAvoidance': 'Total Cost Avoidance',
    'dashboard.topReporter': 'Top Reporter',
    'dashboard.topCostSaver': 'Top Cost Saver',
    'dashboard.topDowntimeSaver': 'Top Downtime Saver',
    'dashboard.participation': 'Participation',
    'dashboard.totalTicketsCountPerPeriod': 'Total Tickets Count Per Period',
    'dashboard.totalTicketsClosedPerPeriod': 'Total Tickets Closed Per Period',
    'dashboard.ticketsClosed': 'Tickets Closed',
    'dashboard.uniqueReporterCoverageRate': 'Unique Reporter & Coverage Rate',
    'dashboard.whoActiveArea': 'Who Active (Area) - Top 10',
    'dashboard.whoActivePlant': 'Who Active (Plant) - Top 10',
    'dashboard.whoActiveEquipment': 'Who Active (Equipment) - Top 10',
    'dashboard.whoActiveUser': 'Who Active (User) - Top 10',
    'dashboard.whenActive': 'When Active - Calendar Heatmap',
    'dashboard.impactAndValue': 'Impact and Value',
    'dashboard.downtimeAvoidanceTrend': 'Downtime Avoidance Trend',
    'dashboard.downtimeAvoidanceTrendByPlant': 'Downtime Avoidance Trend by Plant',
    'dashboard.downtimeAvoidanceTrendByArea': 'Downtime Avoidance Trend by Area',
    'dashboard.downtimeAvoidanceTrendByEquipment': 'Downtime Avoidance Trend by Equipment',
    'dashboard.costAvoidance': 'Cost Avoidance',
    'dashboard.downtimeImpactLeaderboardArea': 'Downtime Impact Leaderboard (Area)',
    'dashboard.downtimeImpactLeaderboardByPlant': 'Downtime Impact Leaderboard (Plant)',
    'dashboard.downtimeImpactLeaderboardByArea': 'Downtime Impact Leaderboard (Area)',
    'dashboard.downtimeImpactLeaderboardByEquipment': 'Downtime Impact Leaderboard (Equipment)',
    'dashboard.costImpactLeaderboardArea': 'Cost Impact Leaderboard (Area)',
    'dashboard.downtimeImpactLeaderboardReporter': 'Downtime Impact Leaderboard (Reporter) - Top 10',
    'dashboard.costImpactLeaderboardReporter': 'Cost Impact Leaderboard (Reporter) - Top 10',
    'dashboard.downtimeImpactByFailureMode': 'Downtime Impact by Failure Mode',
    'dashboard.costImpactByFailureMode': 'Cost Impact by Failure Mode',
    'dashboard.speed': 'Speed',
    'dashboard.ticketAverageResolveDuration': 'Ticket Average Resolve Duration/Case',
    'dashboard.ticketAverageResolveDurationByUser': 'Ticket Average Resolve Duration/Case (By User)',
    'dashboard.ontimeRateByArea': 'Ontime Rate (By Area)',
    'dashboard.ontimeRateByUser': 'Ontime Rate (By User)',
    'dashboard.filters': 'Filters',
    'dashboard.globalFilters': 'Global Filters',
    'dashboard.timeRange': 'Time Range',
    'dashboard.year': 'Year',
    'dashboard.period': 'Period',
    'dashboard.area': 'Area',
    'dashboard.allAreas': 'All Areas',
    'dashboard.thisYear': 'This Year',
    'dashboard.lastYear': 'Last Year',
    'dashboard.thisPeriod': 'This Period',
    'dashboard.selectPeriod': 'Select Period',
    'dashboard.range': 'Range',
    'dashboard.close': 'Close',
    'dashboard.clickToExpand': 'Click to expand →',
    'dashboard.loadingAreas': 'Loading areas...',
    'dashboard.errorLoadingData': 'Error loading data:',
    'dashboard.tickets': 'Tickets',
    'dashboard.ticketsOpened': 'Tickets Opened',
    'dashboard.target': 'Target',
    'dashboard.uniqueReporters': 'Unique Reporters',
    'dashboard.coverageRate': 'Coverage Rate (%)',
    'dashboard.hours': 'Hours',
    'dashboard.minutes': 'Minutes',
    'dashboard.hoursSaved': 'Hours Saved',
    'dashboard.costAvoided': 'Cost Avoided',
    'dashboard.costPerCase': 'Cost per Case (THB/Case)',
    'dashboard.costAvoidanceTHB': 'Cost Avoidance (THB)',
    'dashboard.downtimeHours': 'Downtime Hours',
    'dashboard.caseCount': 'Case Count',
    'dashboard.caseCountByPU': 'Case Count by PU',
    'dashboard.failureModeCode': 'Failure Mode Code',
    'dashboard.failureModeName': 'Failure Mode Name',
    'dashboard.averageResolveTime': 'Average Resolve Time',
    'dashboard.ticketCount': 'Ticket Count',
    'dashboard.ontimeRate': 'Ontime Rate',
    'dashboard.totalFinished': 'Total Finished',
    'dashboard.ontimeFinished': 'Ontime Finished',
    'dashboard.percentage': 'Percentage (%)',
    'dashboard.ticketsReported': 'Tickets Reported',
    'dashboard.ticketsSaved': 'Tickets Saved',
    'dashboard.noData': 'No Data',
    'dashboard.newActivity': 'New Activity',
    'dashboard.activityStopped': 'Activity Stopped',
    'dashboard.noChange': 'No Change',
    'dashboard.increase': 'Increase',
    'dashboard.decrease': 'Decrease',
    'dashboard.less': 'Less',
    'dashboard.more': 'More',
    'dashboard.noDataAvailable': 'No data available',
    'dashboard.clickedOn': 'Clicked on',
    'dashboard.ticketsOnDate': 'tickets',
    
    // Personal KPI Comparison
    'dashboard.personalKPIComparison.title': 'Personal KPI Comparison',
    'dashboard.personalKPIComparison.description': 'Compare personal KPIs across all users with filtering capabilities',
    'dashboard.personalKPIComparison.filters': 'Filters',
    'dashboard.personalKPIComparison.year': 'Year',
    'dashboard.personalKPIComparison.period': 'Period',
    'dashboard.personalKPIComparison.users': 'Users',
    'dashboard.personalKPIComparison.kpi': 'KPI',
    'dashboard.personalKPIComparison.selectYear': 'Select Year',
    'dashboard.personalKPIComparison.selectPeriod': 'Select Period',
    'dashboard.personalKPIComparison.selectKPI': 'Select KPI',
    'dashboard.personalKPIComparison.searchUsers': 'Search users...',
    'dashboard.personalKPIComparison.selectAll': 'Select All',
    'dashboard.personalKPIComparison.deselectAll': 'Deselect All',
    'dashboard.personalKPIComparison.more': 'more',
    'dashboard.personalKPIComparison.noUsersFound': 'No users found',
    'dashboard.personalKPIComparison.summary': 'Showing {userCount} of {totalUsers} users for {year} P{period} - {kpi}',
    'dashboard.personalKPIComparison.totalUsers': 'Total Users',
    'dashboard.personalKPIComparison.outOf': 'out of {total}',
    'dashboard.personalKPIComparison.average': 'Average',
    'dashboard.personalKPIComparison.averageDescription': 'Average value across selected users',
    'dashboard.personalKPIComparison.highest': 'Highest',
    'dashboard.personalKPIComparison.highestDescription': 'Highest value among selected users',
    'dashboard.personalKPIComparison.lowest': 'Lowest',
    'dashboard.personalKPIComparison.lowestDescription': 'Lowest value among selected users',
    'dashboard.personalKPIComparison.dateRange': 'Date Range',
    'dashboard.personalKPIComparison.dateRangeDescription': 'Period {period} of {year}: {startDate} to {endDate}',
    'dashboard.personalKPIComparison.errorLoadingChart': 'Error loading chart data',
    'dashboard.personalKPIComparison.noDataDescription': 'No data available for the selected filters',
    'dashboard.personalKPIComparison.errorFetchingData': 'Failed to fetch KPI comparison data',
    
    // KPI Names
    'dashboard.personalKPIComparison.ticketCountCreated': 'Ticket Count (Created)',
    'dashboard.personalKPIComparison.ticketCountClosed': 'Ticket Count (Closed)',
    'dashboard.personalKPIComparison.downtimeSavedCreated': 'Downtime Saved (Created)',
    'dashboard.personalKPIComparison.downtimeSavedAssigned': 'Downtime Saved (Assigned)',
    'dashboard.personalKPIComparison.costSavedCreated': 'Cost Saved (Created)',
    'dashboard.personalKPIComparison.costSavedAssigned': 'Cost Saved (Assigned)',
    'dashboard.personalKPIComparison.ontimePercentage': 'Ontime Percentage',
    'dashboard.personalKPIComparison.avgResolutionHours': 'Average Resolution (Hours)',
    
    // Filter Mode and Navigation
    'dashboard.personalKPIComparison.filterMode': 'Filter Mode',
    'dashboard.personalKPIComparison.navigation': 'Quick Navigation',
    'dashboard.personalKPIComparison.previous': 'Previous',
    'dashboard.personalKPIComparison.next': 'Next',
    'dashboard.personalKPIComparison.yearSummary': 'Showing {userCount} of {totalUsers} users for {year} - {kpi}',
    'dashboard.personalKPIComparison.periodSummary': 'Showing {userCount} of {totalUsers} users for {year} P{period} - {kpi}',
    'dashboard.personalKPIComparison.yearRangeDescription': 'Company Year {year}: {startDate} to {endDate}',
    'dashboard.personalKPIComparison.periodRangeDescription': 'Period {period} of {year}: {startDate} to {endDate}',
    'dashboard.personalKPIComparison.noDataAvailable': 'No data available',
    'dashboard.personalKPIComparison.export': 'Export',
    'dashboard.personalKPIComparison.department': 'Department',
    'dashboard.personalKPIComparison.selectDepartments': 'Select Departments',
    'dashboard.personalKPIComparison.allDepartments': 'All Departments',
    'dashboard.personalKPIComparison.noDepartmentsFound': 'No departments found',
    
    // Department User KPI Dashboard
    'dashboard.departmentUserKPI.title': 'Department User KPI Dashboard',
    'dashboard.departmentUserKPI.description': 'View year-round performance for all users in department',
    'dashboard.departmentUserKPI.filters': 'Filters',
    'dashboard.departmentUserKPI.selectDepartment': 'Select Department',
    'dashboard.departmentUserKPI.selectYear': 'Year',
    'dashboard.departmentUserKPI.kpiType': 'KPI Type',
    'dashboard.departmentUserKPI.ticketsCreated': 'Tickets Created (Report)',
    'dashboard.departmentUserKPI.ticketsAssigned': 'Tickets Assigned (Fix)',
    'dashboard.departmentUserKPI.noData': 'No users found in selected department',
    'dashboard.departmentUserKPI.noSelection': 'Please select a department to view KPIs',
    'dashboard.departmentUserKPI.selectDepartmentToView': 'Please select a department to view user performance',
    'dashboard.departmentUserKPI.noUsersInDepartment': 'No users found in the selected department',
    'dashboard.departmentUserKPI.totalTickets': 'Total Tickets',
    'dashboard.departmentUserKPI.avgPerPeriod': 'Avg per Period',
    'dashboard.departmentUserKPI.targetAchievement': 'Target Achievement',
    'dashboard.departmentUserKPI.users': 'Users',
    'dashboard.departmentUserKPI.userPerformance': 'User Performance',
    'dashboard.departmentUserKPI.department': 'Department',
    'dashboard.departmentUserKPI.deptCode': 'Dept Code',
    'dashboard.departmentUserKPI.activeUsers': 'Active Users',
    'dashboard.departmentUserKPI.year': 'Year',
    'dashboard.departmentUserKPI.companyYear': 'Company Year',
    'dashboard.departmentUserKPI.totalCreated': 'Total Created',
    'dashboard.departmentUserKPI.totalAssigned': 'Total Assigned',
    'dashboard.departmentUserKPI.avgPerUser': 'Avg per User',
    'dashboard.departmentUserKPI.target': 'Target',
  },
  th: {
    // Common
    'common.loading': 'กำลังโหลด...',
    'common.error': 'ข้อผิดพลาด',
    'common.success': 'สำเร็จ',
    'common.cancel': 'ยกเลิก',
    'common.save': 'บันทึก',
    'common.edit': 'แก้ไข',
    'common.delete': 'ลบ',
    'common.confirm': 'ยืนยัน',
    'common.back': 'กลับ',
    'common.next': 'ถัดไป',
    'common.previous': 'ก่อนหน้า',
    'common.warning': 'คำเตือน',
    'common.search': 'ค้นหาปัญหา',
    'common.clear': 'ล้าง',
    'common.close': 'ปิด',
    'common.apply': 'ตกลง',
    'common.reset': 'รีเซ็ต',
    'common.hideFilters': 'ซ่อนตัวกรอง',
    'common.showFilters': 'แสดงตัวกรอง',
    'common.retry': 'ลองใหม่',
    'common.seeMore': 'ดูเพิ่มเติม',
    'common.showLess': 'แสดงน้อยลง',
    'common.more': 'เพิ่มเติม',
    // Navigation
    'nav.home': 'หน้าหลัก',
    'nav.dashboard': 'แดชบอร์ด',
    'nav.tickets': 'งาน',
    'nav.machines': 'เครื่องจักร',
    'nav.reports': 'รายงาน',
    'nav.users': 'ผู้ใช้',
    'nav.settings': 'ตั้งค่า',
    
    // Authentication
    'auth.login': 'เข้าสู่ระบบ',
    'auth.logout': 'ออกจากระบบ',
    'auth.register': 'ลงทะเบียน',
    'auth.username': 'ชื่อผู้ใช้',
    'auth.password': 'รหัสผ่าน',
    'auth.email': 'อีเมล',
    'auth.firstName': 'ชื่อ',
    'auth.lastName': 'นามสกุล',
    'auth.employeeID': 'รหัสพนักงาน',
    'auth.department': 'แผนก',
    'auth.shift': 'กะ',
    'auth.currentPassword': 'รหัสผ่านปัจจุบัน',
    'auth.newPassword': 'รหัสผ่านใหม่',
    'auth.confirmPassword': 'ยืนยันรหัสผ่าน',
    'auth.changePassword': 'เปลี่ยนรหัสผ่าน',
    'auth.forgotPassword': 'ลืมรหัสผ่าน?',
    'auth.rememberMe': 'จดจำฉัน',
    'auth.loginSuccess': 'เข้าสู่ระบบสำเร็จ',
    'auth.logoutSuccess': 'ออกจากระบบสำเร็จ',
    'auth.registrationSuccess': 'ลงทะเบียนสำเร็จ',
    'auth.passwordChangeSuccess': 'เปลี่ยนรหัสผ่านสำเร็จ',
    
    // User roles
    'role.l1_operator': 'ผู้ปฏิบัติการ L1',
    'role.l2_engineer': 'วิศวกร L2',
    'role.l3_manager': 'ผู้จัดการ L3',
    
    // Dashboard
    'dashboard.welcome': 'ยินดีต้อนรับ',
    'dashboard.plant': 'โรงงาน',
    'dashboard.allPlants': 'ทุกโรงงาน',
    'dashboard.unsavedChanges': 'มีการเปลี่ยนแปลงที่ไม่ได้บันทึก',
    'dashboard.reset': 'รีเซ็ต',
    'dashboard.applyFilters': 'ตกลง',
    'dashboard.pleaseCheckYourConnectionAndTryAgain': 'กรุณาตรวจสอบการเชื่อมต่อและลองใหม่ ถ้าปัญหายังคงมีอยู่ กรุณาติดต่อผู้ดูแลระบบ',
    // Profile  
    'profile.title': 'โปรไฟล์ผู้ใช้',
    'profile.personalInfo': 'ข้อมูลส่วนตัว',
    'profile.workInfo': 'ข้อมูลการทำงาน',
    'profile.lastLogin': 'เข้าสู่ระบบล่าสุด',
    'profile.memberSince': 'เป็นสมาชิกตั้งแต่',
    'profile.profileInformation': 'ข้อมูลโปรไฟล์',
    'profile.changeProfilePicture': 'เปลี่ยนรูปโปรไฟล์',
    'profile.upload': 'อัปโหลด',
    'profile.chooseFile': 'เลือกไฟล์',
    'profile.firstName': 'ชื่อ',
    'profile.lastName': 'นามสกุล',
    'profile.email': 'อีเมล',
    'profile.phone': 'โทรศัพท์',
    'profile.jobTitle': 'ตำแหน่ง',
    'profile.department': 'แผนก',
    'profile.group': 'กลุ่ม',
    'profile.personCode': 'รหัสพนักงาน',
    'profile.selectDepartment': 'เลือกแผนก',
    'profile.noDepartment': 'ไม่มีแผนก',
    'profile.personCodePlaceholder': 'รหัสพนักงาน (สูงสุด 20 ตัวอักษร)',
    'profile.personCodeTooLong': 'รหัสพนักงานต้องไม่เกิน 20 ตัวอักษร',
    'profile.saveChanges': 'บันทึกการเปลี่ยนแปลง',
    'profile.profileUpdated': 'อัปเดตโปรไฟล์แล้ว',
    'profile.failedToUpdateProfile': 'ไม่สามารถอัปเดตโปรไฟล์ได้',
    'profile.avatarUpdated': 'อัปเดตรูปโปรไฟล์แล้ว',
    'profile.failedToUploadAvatar': 'ไม่สามารถอัปโหลดรูปโปรไฟล์ได้',
    'profile.avatarUploadHint': 'เลือกภาพ ตัดแต่ง และจะอัปโหลดโดยอัตโนมัติ',
    'profile.applyAndUpload': 'ใช้และอัปโหลด',
    'profile.uploading': 'กำลังอัปโหลด...',
    'profile.invalidImageFile': 'กรุณาเลือกไฟล์ภาพที่ถูกต้อง',
    'profile.imageTooLarge': 'ไฟล์ภาพใหญ่เกินไป (สูงสุด 10MB)',
    'profile.failedToLoadImage': 'ไม่สามารถโหลดภาพได้',
    'profile.lineNotifications': 'การแจ้งเตือน LINE',
    'profile.lineUserId': 'LINE User ID (สำหรับการแจ้งเตือน)',
    'profile.enterLineId': 'กรอกรหัส LineID ของคุณ',
    'profile.sendTestLineNotification': 'ทดสอบการแจ้งเตือนผ่าน LINE',
    'profile.ensureLineIdSet': 'ตรวจสอบให้แน่ใจว่ารหัส LineID ของคุณถูกตั้งค่าไว้ด้านบน',
    'profile.testNotificationSent': 'ส่งการแจ้งเตือนทดสอบไปยัง LINE ของคุณแล้ว',
    'profile.failedToSendTestNotification': 'ไม่สามารถส่งการแจ้งเตือนทดสอบได้',
    'profile.pleaseEnterLineId': 'กรุณากรอก LINE ID เพื่อทดสอบ',
    'profile.lineIdChangedNotSaved': 'LINE ID ของคุณถูกเปลี่ยนแปลงแล้วแต่ยังไม่ได้บันทึก กรุณาคลิก "บันทึก LINE ID" เพื่อบันทึกถาวร',
    'profile.testWillUseCurrentInput': 'การทดสอบจะใช้ LINE ID ที่คุณกรอกไว้ด้านบน',
    'profile.testWillUseSavedLineId': 'การทดสอบจะใช้ LINE ID ที่บันทึกไว้ของคุณ',
    'profile.saveLineId': 'บันทึก LINE ID',
    'profile.saving': 'กำลังบันทึก...',
    'profile.lineIdUpdated': 'อัปเดต LINE ID สำเร็จ',
    'profile.failedToUpdateLineId': 'ไม่สามารถอัปเดต LINE ID ได้',
    'profile.note': 'หมายเหตุ',
    'profile.changePassword': 'เปลี่ยนรหัสผ่าน',
    'profile.currentPassword': 'รหัสผ่านปัจจุบัน',
    'profile.newPassword': 'รหัสผ่านใหม่',
    'profile.passwordChanged': 'เปลี่ยนรหัสผ่านแล้ว',
    'profile.failedToChangePassword': 'ไม่สามารถเปลี่ยนรหัสผ่านได้',
    'profile.lineHelpTitle': 'วิธีรับ LINE User ID ของคุณ',
    'profile.lineHelpDescription': 'ทำตามขั้นตอนเหล่านี้เพื่อรับ LINE User ID สำหรับการแจ้งเตือน:',
    'profile.step1Title': 'เพิ่มบัญชี LINE Official ของเรา',
    'profile.step1Description': 'สแกน QR code ด้านล่างหรือคลิกลิงก์เพื่อเพิ่มบัญชี LINE ของเราเป็นเพื่อน',
    'profile.addLineFriend': 'เพิ่มเพื่อน LINE',
    'profile.step2Title': 'ส่งข้อความ "Line ID"',
    'profile.step2Description': 'เปิดแชทกับบัญชี LINE ของเราและส่งข้อความ:',
    'profile.step3Title': 'คัดลอก User ID ของคุณ',
    'profile.step3Description': 'คัดลอก User ID ที่ได้รับและวางในช่องด้านบน',
    'profile.gotIt': 'เข้าใจแล้ว!',
    'profile.cropAvatar': 'ตัดรูปโปรไฟล์',
    'profile.zoom': 'ซูม',
    'profile.cancel': 'ยกเลิก',
    'profile.apply': 'ใช้',
    'profile.failedToCropImage': 'ไม่สามารถตัดรูปภาพได้',
    'profile.lineAccount': 'บัญชี LINE',
    'profile.linkedLineAccount': 'บัญชี LINE ที่เชื่อมโยง',
    'profile.lineDisplayName': 'ชื่อแสดงใน LINE',
    'profile.lineProfilePicture': 'รูปโปรไฟล์ LINE',
    'profile.unlinkLineAccount': 'ยกเลิกการเชื่อมโยงบัญชี LINE',
    'profile.unlinkConfirmationTitle': 'ยกเลิกการเชื่อมโยงบัญชี LINE',
    'profile.unlinkConfirmationMessage': 'คุณแน่ใจหรือไม่ว่าต้องการยกเลิกการเชื่อมโยงบัญชี LINE? คุณจะไม่ได้รับการแจ้งเตือนผ่าน LINE อีกต่อไป',
    'profile.unlinkSuccess': 'ยกเลิกการเชื่อมโยงบัญชี LINE สำเร็จ',
    'profile.unlinkFailed': 'ไม่สามารถยกเลิกการเชื่อมโยงบัญชี LINE ได้',
    'profile.logoutInstructionTitle': 'ยกเลิกการเชื่อมโยงบัญชีแล้ว',
    'profile.logoutInstructionMessage': 'บัญชี LINE ของคุณได้ถูกยกเลิกการเชื่อมโยงแล้ว กรุณาออกจากระบบและเข้าสู่ระบบใหม่เพื่อเชื่อมโยงบัญชี LINE ใหม่',
    'profile.logoutNow': 'ออกจากระบบตอนนี้',
    'profile.lineAccountNotLinked': 'ไม่มีบัญชี LINE เชื่อมโยง',
    'profile.failedToGetLineProfile': 'ไม่สามารถดึงข้อมูลโปรไฟล์ LINE ได้',
    'profile.unsavedChanges': 'มีการเปลี่ยนแปลงที่ยังไม่ได้บันทึก',
    
    // Settings
    'settings.title': 'ตั้งค่า',
    'settings.appearance': 'ลักษณะ',
    'settings.language': 'ภาษา',
    'settings.notifications': 'การแจ้งเตือน',
    'settings.security': 'ความปลอดภัย',
    
    // Theme
    'theme.light': 'สว่าง',
    'theme.dark': 'มืด',
    'theme.auto': 'อัตโนมัติ',
    
    // Language
    'language.english': 'English',
    'language.thai': 'ไทย',
    
    // Errors
    'error.invalidCredentials': 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
    'error.userNotFound': 'ไม่พบผู้ใช้',
    'error.unauthorized': 'การเข้าถึงไม่ได้รับอนุญาต',
    'error.forbidden': 'การเข้าถึงถูกห้าม',
    'error.notFound': 'ไม่พบหน้า',
    'error.serverError': 'ข้อผิดพลาดของเซิร์ฟเวอร์',
    'error.networkError': 'ข้อผิดพลาดเครือข่าย',
    'error.validationError': 'ข้อผิดพลาดการตรวจสอบ',
    
    // Validation
    'validation.required': 'กรุณากรอกข้อมูลในช่องนี้',
    'validation.email': 'กรุณากรอกอีเมลที่ถูกต้อง',
    'validation.passwordLength': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
    'validation.passwordMatch': 'รหัสผ่านไม่ตรงกัน',
    'validation.usernameLength': 'ชื่อผู้ใช้ต้องมีอย่างน้อย 3 ตัวอักษร',
    
    // Homepage specific
    'homepage.welcome': 'ยินดีต้อนรับ',
    'homepage.quickActions': 'ทางลัด',
    'homepage.tasks': 'งาน',
    'homepage.performance': 'ประสิทธิภาพ',
    'homepage.pendingTickets': 'งานที่รอดำเนินการ',
    'homepage.personal': 'ส่วนตัว',
    'homepage.team': 'ทีม',
    'homepage.createTicket': 'รายงานความผิดปกติ',
    'homepage.viewTickets': 'ดูรายงานทั้งหมด',
    'homepage.reportNewIssue': 'รายงานความผิดปกติหรือคำขอใหม่',
    'homepage.checkTicketStatus': 'ตรวจสอบสถานะงานของคุณ',
    'homepage.loadingPendingTickets': 'กำลังโหลดงานที่รอดำเนินการ...',
    'homepage.errorLoadingTickets': 'ข้อผิดพลาดในการโหลดงาน',
    'homepage.noPendingTickets': 'ไม่มีงานที่รอดำเนินการ',
    'homepage.allTicketsUpToDate': 'งานทั้งหมดของคุณเป็นปัจจุบันแล้ว!',
    'homepage.youCreatedThisTicket': 'คุณรายงานความผิดปกตินี้',
    'homepage.requiresYourApproval': 'ต้องการการอนุมัติจากคุณ',
    'homepage.viewOnly': 'ดูเท่านั้น',
    'homepage.myFinishCasesPerPeriod': 'จำนวนเคสที่ฉันแก้ไขเสร็จตามช่วงเวลา',
    'homepage.myReportCasePerPeriod': 'จำนวนเคสที่ฉันรายงานตามช่วงเวลา',
    'homepage.setupKPI': 'ตั้งค่า KPI',
    'homepage.errorLoadingChartData': 'ข้อผิดพลาดในการโหลดข้อมูลแผนภูมิ',
    'homepage.noFinishedTicketData': 'ไม่มีข้อมูลงานที่เสร็จสิ้น',
    'homepage.finishSomeTickets': 'ทำงานให้เสร็จเพื่อดูประสิทธิภาพของคุณ!',
    'homepage.noTicketDataAvailable': 'ไม่มีข้อมูลงาน',
    'homepage.startCreatingTickets': 'เริ่มรายงานความผิดปกติเพื่อดูประสิทธิภาพของคุณ!',
    'homepage.asReporter': 'ในฐานะผู้รายงาน (ฉันช่วยโดยการรายงาน)',
    'homepage.asActionPerson': 'ในฐานะผู้ดำเนินการ (ฉันช่วยโดยการแก้ไข)',
    'homepage.errorLoadingKPIData': 'ข้อผิดพลาดในการโหลดข้อมูล KPI',
    'homepage.loadingPersonalMetrics': 'กำลังโหลดเมตริกส่วนตัว...',
    'homepage.noKPIDataAvailable': 'ไม่มีข้อมูล KPI',
    'homepage.myReportsCreated': 'จำนวนเคสที่ฉันรายงาน',
    'homepage.downtimeAvoidedByMyReports': 'เวลาหยุดทำงานที่หลีกเลี่ยงได้จากรายงานของฉัน',
    'homepage.costAvoidedByMyReports': 'ต้นทุนที่หลีกเลี่ยงได้จากรายงานของฉัน',
    'homepage.casesIFixed': 'จำนวนเคสที่ฉันแก้ไข',
    'homepage.downtimeIFixed': 'เวลาหยุดทำงานที่หลีกเลี่ยงได้จากการแก้ไข',
    'homepage.costIFixed': 'ต้นทุนที่หลีกเลี่ยงได้จากการแก้ไข',
    'homepage.noChange': 'ไม่มีการเปลี่ยนแปลง',
    'homepage.teamPerformance': 'ประสิทธิภาพทีม',
    'homepage.teamPerformanceComingSoon': 'เมตริกประสิทธิภาพทีมจะมาเร็วๆ นี้...',
    'homepage.filters': 'ตัวกรอง',
    'homepage.range': 'ช่วง',
    'homepage.currentSelection': 'การเลือกปัจจุบัน',
    'homepage.thisYear': 'ปีนี้',
    'homepage.lastYear': 'ปีที่แล้ว',
    'homepage.thisPeriod': 'ช่วงเวลา',
    'homepage.FinishedTickets': 'งานที่เสร็จสิ้น',
    'homepage.target': 'เป้าหมาย',
    'homepage.myTickets': 'งานของฉัน',
    'homepage.failedToFetchPendingTickets': 'ไม่สามารถดึงงานที่รอดำเนินการได้',
    'homepage.failedToFetchPersonalTicketData': 'ไม่สามารถดึงข้อมูลงานส่วนตัวได้',
    'homepage.failedToFetchPersonalFinishedTicketData': 'ไม่สามารถดึงข้อมูลงานที่เสร็จสิ้นส่วนตัวได้',
    'homepage.failedToFetchPersonalKPIData': 'ไม่สามารถดึงข้อมูล KPI ส่วนตัวได้',
    // Relationship-based ticket section titles
    'homepage.escalatedTickets': 'งานที่ถูกส่งต่อ',
    'homepage.ticketsToAccept': 'งานที่รอเจ้าของพื้นที่ตอบรับ',
    'homepage.ticketsToClose': 'งานที่รอผู้จัดการอนุมัติปิด',
    'homepage.ticketsToReview': 'งานที่รอผู้่แจ้งต้องตรวจสอบผลการแก้ไขและอนุมัต้ิ',
    'homepage.ticketsToReviewRejected': 'งานที่ต้องตรวจสอบ (ถูกปฏิเสธ)',
    'homepage.ticketsToPlan': 'งานที่ต้องวางแผน',
    'homepage.myAssignedTickets': 'งานที่ได้รับมอบหมาย',
    'homepage.myCreatedTickets': 'งานที่ฉันสร้าง',
    'homepage.otherTickets': 'งานอื่นๆ',
    // Mobile card labels
    'homepage.accepted': 'อนุมัติแล้ว',
    'homepage.acceptedBy': 'อนุมัติโดย',
    'homepage.escalated': 'ส่งต่อแล้ว',
    'homepage.escalatedBy': 'ส่งต่อโดย',
    'homepage.reviewed': 'ตรวจสอบแล้ว',
    'homepage.reviewedBy': 'ตรวจสอบโดย',
    'homepage.finished': 'เสร็จสิ้นแล้ว',
    'homepage.finishedBy': 'เสร็จสิ้นโดย',
    'homepage.rejected': 'ปฏิเสธแล้ว',
    'homepage.rejectedBy': 'ปฏิเสธโดย',
    'homepage.scheduledStart': 'กำหนดเวลาเริ่ม',
    'homepage.scheduledFinish': 'กำหนดเวลาเสร็จ',
    'homepage.createdBy': 'สร้างโดย',
    'homepage.created': 'สร้างเมื่อ',
    'homepage.assignedTo': 'มอบหมายให้',
    
    // Personal KPI Modal
    'personalKPI.title': 'การตั้งค่าเป้าหมาย KPI ส่วนตัว',
    'personalKPI.reportCases': 'กรณีรายงาน',
    'personalKPI.fixCases': 'กรณีแก้ไข',
    'personalKPI.error': 'ข้อผิดพลาด',
    'personalKPI.success': 'สำเร็จ',
    'personalKPI.validationError': 'ข้อผิดพลาดการตรวจสอบ',
    'personalKPI.failedToFetchExistingTargets': 'ไม่สามารถดึงเป้าหมายที่มีอยู่ได้',
    'personalKPI.userInformationNotAvailable': 'ข้อมูลผู้ใช้ไม่พร้อมใช้งาน',
    'personalKPI.failedToSavePersonalTargets': 'ไม่สามารถบันทึกเป้าหมายส่วนตัวได้',
    'personalKPI.user': 'ผู้ใช้',
    'personalKPI.personNo': 'รหัสพนักงาน',
    'personalKPI.year': 'ปี',
    'personalKPI.unit': 'หน่วย',
    'personalKPI.case': 'เคส',
    'personalKPI.thb': 'บาท',
    'personalKPI.percent': 'เปอร์เซ็นต์',
    'personalKPI.existingTargetsWarning': 'คุณมีเป้าหมายที่ตั้งไว้แล้วสำหรับ {type} ในปี {year} การบันทึกค่าใหม่จะแทนที่เป้าหมายเดิม',
    'personalKPI.periodValues': 'ค่าเป้าหมายตามช่วงเวลา',
    'personalKPI.copyP1ToAll': 'คัดลอก P1 ไปทุกช่วงเวลา',
    'personalKPI.resetForm': 'รีเซ็ตฟอร์ม',
    'personalKPI.cancel': 'ยกเลิก',
    'personalKPI.saveTargets': 'บันทึกเป้าหมาย',
    'personalKPI.saving': 'กำลังบันทึก...',
    'personalKPI.fillAllPeriods': 'กรุณากรอกค่าสำหรับทุกช่วงเวลา: {periods}',
    'personalKPI.targetsSavedSuccess': 'บันทึกเป้าหมายส่วนตัวสำเร็จสำหรับ {type} ในปี {year}',
    'personalKPI.report': 'รายงาน',
    'personalKPI.fix': 'แก้ไข',
    'personalFilter.title': 'ตัวกรองประสิทธิภาพส่วนตัว',
    'personalFilter.timeRange': 'ช่วงเวลา',
    'personalFilter.selectTimeRange': 'เลือกช่วงเวลา',
    'personalFilter.thisYear': 'ปีนี้',
    'personalFilter.lastYear': 'ปีที่แล้ว',
    'personalFilter.thisPeriod': 'ช่วงเวลานี้',
    'personalFilter.selectPeriod': 'เลือกช่วงเวลา',
    'personalFilter.year': 'ปี',
    'personalFilter.period': 'ช่วงเวลา',
    'personalFilter.applyFilters': 'ใช้ตัวกรอง',
    'personalFilter.unsavedChanges': 'มีการเปลี่ยนแปลงที่ยังไม่ได้บันทึก',
    
    // Common chart labels
    'chart.FinishedTickets': 'งานที่เสร็จสิ้น',
    'chart.target': 'เป้าหมาย',
    'chart.myTickets': 'รายงานของฉัน',
    
    // Ticket Management
    'ticket.create': 'รายงานความผิดปกติ',
    'ticket.edit': 'แก้ไขงาน',
    'ticket.view': 'ดูงาน',
    'ticket.title': 'หัวข้อ',
    'ticket.description': 'รายละเอียด',
    'ticket.status': 'สถานะ',
    'ticket.priority': 'ความสำคัญ',
    'ticket.severity': 'ความรุนแรง',
    'ticket.pucode': 'PUCODE',
    'ticket.area': 'พื้นที่',
    'ticket.created': 'สร้างเมื่อ',
    'ticket.updated': 'อัปเดตเมื่อ',
    'ticket.assignee': 'ผู้รับผิดชอบ',
    'ticket.reporter': 'ผู้รายงาน',
    'ticket.reportAbnormalFinding': 'รายงานความผิดปกติ',
    'ticket.briefDescription': 'คำอธิบายสั้นๆ เกี่ยวกับความผิดปกติ',
    'ticket.detailedDescription': 'คำอธิบายรายละเอียดเกี่ยวกับความผิดปกติ รวมถึงอาการและการสังเกต',
    'ticket.titleRequired': 'กรุณากรอกหัวข้อ',
    'ticket.descriptionRequired': 'กรุณากรอกรายละเอียด',
    'ticket.pucodeRequired': 'กรุณากรอก PUCODE',
    'ticket.machineName': 'ชื่อเครื่องจักร', // Added machine name
    'ticket.ticketCreatedSuccess': 'สร้างงานสำเร็จ',
    'ticket.ticketUpdatedSuccess': 'อัปเดตงานสำเร็จ',
    'ticket.failedToCreateTicket': 'ไม่สามารถสร้างงานได้',
    'ticket.failedToUpdateTicket': 'ไม่สามารถอัปเดตงานได้',
    'ticket.failedToFetchTickets': 'ไม่สามารถดึงข้อมูลงานได้',
    'ticket.noTicketsFound': 'ไม่พบรายงาน',
    'ticket.loadingTickets': 'กำลังโหลดงาน...',
    'ticket.errorLoadingTickets': 'ข้อผิดพลาดในการโหลดงาน',
    'ticket.searchTickets': 'ค้นหางาน...',
    'ticket.filterByStatus': 'กรองตามสถานะ',
    'ticket.filterByPriority': 'กรองตามความสำคัญ',
    'ticket.filterBySeverity': 'กรองตามความรุนแรง',
    'ticket.allStatuses': 'ทุกสถานะ',
    'ticket.allPriorities': 'ทุกความสำคัญ',
    'ticket.allSeverities': 'ทุกความรุนแรง',
    'ticket.allAreas': 'ทุกพื้นที่',
    'ticket.allUsers': 'ทุกผู้ใช้',
    'ticket.searchUsers': 'ค้นหาผู้ใช้...',
    'ticket.open': 'เปิด',
    'ticket.assigned': 'มอบหมายแล้ว',
    'ticket.inProgress': 'กำลังดำเนินการ',
    'ticket.pending': 'รอดำเนินการ',
    'ticket.resolved': 'แก้ไขแล้ว',
    'ticket.reviewed': 'ตรวจสอบแล้ว',
    'ticket.closed': 'ปิด',
    'ticket.cancelled': 'ยกเลิก',
    'ticket.rejectedPendingL3Review': 'ปฏิเสธ (รอแพลนเนอร์ตรวจสอบ)',
    'ticket.rejectedFinal': 'ปฏิเสธ (สุดท้าย)',
    
    // Critical levels
    'ticket.critical': 'ความรุนแรง',
    'ticket.criticalLevel1': 'ไม่มีข้อมูล',
    'ticket.criticalLevel2': 'ไม่มีข้อมูล',
    'ticket.criticalLevel3': 'ไม่มีข้อมูล',
    'ticket.criticalLevel4': 'ไม่มีข้อมูล',
    'ticket.criticalLevel5': 'การผลิตหยุด',
    'ticket.criticalLevel6': 'กำลังการผลิตลดลง',
    'ticket.criticalLevel7': 'ไม่มีผลกระทบ',
    'ticket.allCriticalLevels': 'ทุกระดับความสำคัญ',
    
    'ticket.finished': 'เสร็จสิ้น',
    'ticket.escalated': 'ยกระดับ',
    'ticket.reopenedInProgress': 'เปิดใหม่',
    'ticket.low': 'ต่ำ',
    'ticket.medium': 'ปานกลาง',
    'ticket.high': 'สูง',
    'ticket.normal': 'ปกติ',
    'ticket.urgent': 'ด่วน',
    'ticket.costAvoidance': 'ต้นทุนที่หลีกเลี่ยงได้',
    'ticket.downtimeAvoidance': 'เวลาหยุดทำงานที่หลีกเลี่ยงได้ (ชั่วโมง)',
    'ticket.failureMode': 'ลักษณะปัญหา',
    'ticket.attachments': 'ไฟล์แนบ',
    'ticket.addAttachment': 'เพิ่มไฟล์แนบ',
    'ticket.removeAttachment': 'ลบไฟล์แนบ',
    'ticket.comments': 'ความคิดเห็น',
    'ticket.addComment': 'เพิ่มความคิดเห็น',
    'ticket.noComments': 'ยังไม่มีความคิดเห็น',
    'ticket.history': 'ประวัติ',
    'ticket.timeline': 'ไทม์ไลน์',
    'ticket.actions': 'การดำเนินการ',
    'ticket.approve': 'อนุมัติ',
    'ticket.reject': 'ปฏิเสธ',
    'ticket.assign': 'มอบหมาย',
    'ticket.unassign': 'ยกเลิกการมอบหมาย',
    'ticket.approveReview': 'อนุมัติ',
    'ticket.reviewReason': 'เหตุผลการตรวจสอบ',
    'ticket.approveClose': 'อนุมัติการปิด',
    'ticket.close': 'ปิด',
    'ticket.reopen': 'เปิดใหม่',
    'ticket.scheduleStart': 'วันที่วางแผนเริ่มต้น',
    'ticket.scheduleFinish': 'วันที่วางแผนสิ้นสุด',
    'ticket.assignTo': 'มอบหมาย',
    'ticket.assignedTo': 'มอบหมายให้',
    'ticket.pleaseSelectAssignee': 'กรุณาเลือกผู้รับผิดชอบ',
    'ticket.plan': 'วางแผน',
    'ticket.start': 'เริ่มงาน',
    'ticket.actualStartTime': 'เวลาที่เริ่มงานจริง',
    'ticket.actualStartTimeHelp': 'ค่าเริ่มต้นเป็นเวลาปัจจุบัน แต่สามารถปรับได้ตามต้องการ',
    'ticket.actualStartTimeEditHelp': 'แก้ไขเวลาที่เริ่มงานจริงหากแตกต่างจากเวลาที่เริ่มงาน',
    'ticket.actualFinishTime': 'เวลาที่เสร็จงานจริง',
    'ticket.actualFinishTimeHelp': 'เวลาที่งานเสร็จสิ้นจริง',
    'ticket.duplicate': 'ทำซ้ำ',
    'ticket.duplicateTicket': 'ทำซ้ำงาน',
    'ticket.originalTicket': 'งานต้นฉบับ',
    'ticket.relatedTickets': 'งานที่เกี่ยวข้อง',
    'ticket.dependencies': 'การพึ่งพา',
    'ticket.tags': 'แท็ก',
    'ticket.addTag': 'เพิ่มแท็ก',
    'ticket.removeTag': 'ลบแท็ก',
    'ticket.wizard': 'ตัวช่วยสร้างงาน',
    'ticket.wizardStep1': 'ขั้นตอนที่ 1: ข้อมูลพื้นฐาน',
    'ticket.wizardStep2': 'ขั้นตอนที่ 2: รายละเอียด',
    'ticket.wizardStep3': 'ขั้นตอนที่ 3: ตรวจสอบ',
    'ticket.wizardNext': 'ถัดไป',
    'ticket.wizardPrevious': 'ก่อนหน้า',
    'ticket.wizardFinish': 'เสร็จสิ้น',
    'ticket.wizardCancel': 'ยกเลิก',
    'ticket.wizardBack': 'กลับ',
    'ticket.wizardReview': 'ตรวจสอบ',
    'ticket.wizardConfirm': 'ยืนยัน',
    'ticket.wizardSuccess': 'สร้างงานสำเร็จ!',
    'ticket.wizardError': 'ข้อผิดพลาดในการสร้างงาน',
    'ticket.wizardValidationError': 'กรุณากรอกข้อมูลในช่องที่จำเป็น',
    'ticket.wizardSelectPlant': 'เลือกโรงงาน',
    'ticket.wizardSelectArea': 'เลือกพื้นที่',
    'ticket.wizardSelectLine': 'เลือกไลน์',
    'ticket.wizardSelectMachine': 'เลือกเครื่องจักร',
    'ticket.wizardSelectPUCODE': 'เลือก PUCODE',
    'ticket.wizardSelectFailureMode': 'เลือกลักษณะปัญหา',
    'ticket.wizardUploadImages': 'อัปโหลดรูปภาพ',
    'ticket.wizardDragDropImages': 'ลากและวางรูปภาพที่นี่ หรือคลิกเพื่อเลือก',
    'ticket.wizardImagePreview': 'ตัวอย่างรูปภาพ',
    'ticket.wizardRemoveImage': 'ลบรูปภาพ',
    'ticket.wizardMaxImages': 'อัปโหลดได้สูงสุด 5 รูป',
    'ticket.wizardImageSize': 'ขนาดรูปภาพควรน้อยกว่า 5MB',
    'ticket.wizardImageFormat': 'รองรับเฉพาะรูปแบบ JPG, PNG, GIF',
    'ticket.deleteConfirm': 'คุณแน่ใจหรือไม่ว่าต้องการลบงานนี้?',
    
    // Hierarchical selection
    'ticket.selectionModeSearch': 'ค้นหา',
    'ticket.selectionModeHierarchy': 'เรียกดูตามลำดับชั้น',
    'ticket.selectPlant': 'เลือกโรงงาน',
    'ticket.selectArea': 'เลือกพื้นที่',
    'ticket.selectLine': 'เลือกไลน์',
    'ticket.selectMachine': 'เลือกเครื่องจักร',
    'ticket.selectNumber': 'เลือกหมายเลข',
    'ticket.hierarchyPathSelected': 'เส้นทางที่เลือก',
    'ticket.hierarchyHelpText': 'ค้นหาผ่านตัวกรอง คุณสามารถเลือกรายงานที่ทุกระดับ - โรงงาน, พื้นที่, ไลน์, หรือเครื่องจักร',
    'ticket.selectLineOrMachine': 'เลือกไลน์หรือเครื่องจักร',
    'ticket.lineOption': 'ไลน์: {name}',
    'ticket.machineOption': 'เครื่องจักร: {name}',
    'ticket.noneOption': 'ไม่มี (ไม่มีไลน์)',
    'ticket.ticketDeletedSuccess': 'ลบงานสำเร็จ',
    'ticket.failedToDeleteTicket': 'ไม่สามารถลบงานได้',
    'ticket.delete': 'ลบ',
    'ticket.deleteTicket': 'ลบงาน',
    'ticket.deleteReason': 'เหตุผลในการลบ',
    'ticket.deleteReasonPlaceholder': 'กรุณาระบุเหตุผลในการลบงานนี้...',
    'ticket.deleteReasonRequired': 'จำเป็นต้องระบุเหตุผลในการลบ',
    'ticket.deleteWarning': 'การกระทำนี้ไม่สามารถยกเลิกได้ งานจะถูกลบอย่างถาวร',
    'ticket.deleting': 'กำลังลบ...',
    'ticket.confirmDelete': 'ยืนยันการลบ',
    'ticket.warning': 'คำเตือน',
    'ticket.fileSkipped': 'ข้ามไฟล์บางไฟล์ รับเฉพาะไฟล์รูปภาพเท่านั้น',
    'ticket.fileSizeExceeded': 'ไฟล์ถูกข้าม ขนาดไฟล์สูงสุด 10MB',
    'ticket.searchMachines': 'กำลังค้นหา...',
    'ticket.failedToSearchPU': 'ไม่สามารถค้นหาได้ กรุณาลองใหม่',
    'ticket.atLeastOneAttachment': 'ต้องมีไฟล์แนบอย่างน้อย 1 ไฟล์',
    'ticket.selectedPU': 'หน่วยการผลิตที่เลือก',
    'ticket.typeToSearch': 'พิมพ์อย่างน้อย 2 ตัวอักษรเพื่อค้นหาด้วยชื่อ PU หรือ PUCODE',
    'ticket.attachImages': 'แนบรูปภาพปัญหา',
    'ticket.dragDropFiles': 'ลากและวางไฟล์ที่นี่ หรือ',
    'ticket.dropFilesHere': 'วางไฟล์ที่นี่',
    'ticket.browseFiles': 'เลือกไฟล์',
    'ticket.imageUploadInfo': 'PNG, JPG หรือ JPEG สูงสุด 10MB ต่อไฟล์ รูปภาพจะอัปโหลดหลังจากสร้างงานแล้ว',
    'ticket.selectedFiles': 'เลือกแล้ว:',
    'ticket.clearAll': 'ลบทั้งหมด',
    'ticket.remove': 'ลบ',
    'ticket.problemTitle': 'หัวข้อปัญหา',
    'ticket.addConciseTitle': 'เพิ่มหัวข้อปัญหาที่กระชับ',
    'ticket.describeAbnormalFinding': 'อธิบายความผิดปกติอย่างละเอียด',
    'ticket.selectSeverity': 'เลือกความรุนแรง',
    'ticket.selectPriority': 'เลือกความสำคัญ',
    'ticket.submitReport': 'ส่งรายงาน',
    'ticket.creating': 'กำลังสร้าง...',
    'ticket.uploadingImages': 'กำลังอัปโหลดรูปภาพ...',
    'ticket.ticketNumber': 'หมายเลขงาน',
    'ticket.createdBy': 'สร้างโดย',
    'ticket.unassigned': 'ยังไม่ได้มอบหมาย',
    'ticket.to': 'ถึง',
    'ticket.of': 'จาก',
    'ticket.export': 'ส่งออก',
    'ticket.exportComingSoon': 'ส่งออก (เร็วๆ นี้)',
    'ticket.exportTickets': 'ส่งออกงานเป็นไฟล์ CSV',
    'ticket.noTicketsToExport': 'ไม่มีงานที่จะส่งออก',
    'ticket.exportSuccess': 'ส่งออกงานเรียบร้อยแล้ว',
    'ticket.ticketNotFound': 'ไม่พบรายงาน',
    'ticket.ticketNotFoundDescription': 'ไม่พบรายงานที่ร้องขอ',
    'ticket.backToTickets': 'กลับไปยังรายการงาน',
    'ticket.accept': 'รับงาน',
    'ticket.overrideAccept': 'ข้ามและรับงาน',
    'ticket.finalReject': 'ปฏิเสธขั้นสุดท้าย',
    'ticket.finish': 'เสร็จสิ้น',
    'ticket.escalate': 'ยกระดับ',
    'ticket.reassign': 'มอบหมาย',
    'ticket.imageEvidence': 'หลักฐานรูปภาพ',
    'ticket.before': 'ก่อน',
    'ticket.after': 'หลัง',
    'ticket.photo': 'รูป',
    'ticket.photos': 'รูป',
    'ticket.noBeforeImages': 'ยังไม่ได้อัปโหลดรูปภาพก่อน',
    'ticket.noAfterImages': 'ยังไม่ได้อัปโหลดรูปภาพหลัง',
    'ticket.addProblemEvidence': 'เพิ่มหลักฐานปัญหา',
    'ticket.shareImprovementResults': 'แชร์ผลการปรับปรุง',
    'ticket.dragDropOrChoose': 'ลากและวางหรือเลือกไฟล์เพื่ออัปโหลด',
    'ticket.uploading': 'กำลังอัปโหลด...',
    'ticket.upload': 'อัปโหลด',
    'ticket.image': 'รูปภาพ',
    'ticket.images': 'รูปภาพ',
    'ticket.uploadDisabled': 'ปิดการอัปโหลดสำหรับงานที่ปิดหรือปฏิเสธแล้ว',
    'ticket.afterGalleryUnlock': 'แกลเลอรี่หลังจะปลดล็อกเมื่องานนี้ได้รับการยอมรับหรือเปลี่ยนเป็นกำลังดำเนินการ',
    'ticket.commentPlaceholder': 'แชร์การอัปเดตหรือถามคำถาม...',
    'ticket.failedToAddComment': 'ไม่สามารถเพิ่มความคิดเห็นได้',
    'ticket.postComment': 'โพสต์ความคิดเห็น',
    'ticket.ticketInformation': 'ข้อมูลงาน',
    'ticket.location': 'ตำแหน่ง',
    'ticket.scheduledStartdate': 'วันที่กำหนดเริ่มต้น',
    'ticket.scheduledFinishdate': 'วันที่กำหนดเสร็จสิ้น',
    'ticket.actualStartdate': 'วันที่เริ่มต้นจริง',
    'ticket.actualFinishdate': 'วันที่เสร็จสิ้นจริง',
    'ticket.noLocationDetails': 'ไม่มีรายละเอียดตำแหน่ง',
    'ticket.hours': 'ชั่วโมง',
    'ticket.workflowTimeline': 'ไทม์ไลน์การทำงาน',
    'ticket.ticketCreated': 'สร้างงานแล้ว',
    'ticket.by': 'โดย',
    'ticket.ticketAssigned': 'มอบหมายงานแล้ว',
    'ticket.statusChangedTo': 'เปลี่ยนสถานะเป็น',
    'ticket.rejectionReason': 'เหตุผลการปฏิเสธ *',
    'ticket.closeReason': 'เหตุผลการปิด',
    'ticket.reopenReason': 'เหตุผลการเปิดใหม่',
    'ticket.notes': 'หมายเหตุ',
    'ticket.rejectionReasonRequired': 'ต้องระบุเหตุผลการปฏิเสธ',
    'ticket.scheduledFinishedate': 'วันที่กำหนดเสร็จสิ้น',
    'ticket.scheduledFinishedateRequired': 'ต้องระบุวันที่กำหนดเสร็จสิ้น',
    'ticket.downtimeAvoidanceHours': 'เวลาหยุดทำงานที่หลีกเลี่ยงได้ (ชั่วโมง)',
    'ticket.costAvoidanceTHB': 'ต้นทุนที่หลีกเลี่ยงได้ (บาท)',
    'ticket.selectFailureMode': 'เลือกลักษณะปัญหา',
    'ticket.satisfactionRating': 'คะแนนความพึงพอใจ',
    'ticket.newAssignee': 'ผู้รับผิดชอบใหม่ *',
    'ticket.searchL2L3User': 'ค้นหาผู้ใช้ ซ่อมบำรุง/แพลนเนอร์ ตามชื่อ/อีเมล',
    'ticket.searching': 'กำลังค้นหา...',
    'ticket.noUsersFound': 'ไม่พบผู้ใช้',
    'ticket.pleaseSelectNewAssignee': 'กรุณาเลือกผู้รับผิดชอบใหม่',
    'ticket.selectedUserId': 'รหัสผู้ใช้ที่เลือก',
    'ticket.escalateToL3User': 'ยกระดับไปยังแพลนเนอร์',
    'ticket.searchL3User': 'ค้นหาผู้ใช้แพลนเนอร์ ตามชื่อ/อีเมล',
    'ticket.noL3UsersFound': 'ไม่พบผู้ใช้แพลนเนอร์',
    'ticket.selectedL3UserId': 'รหัสผู้ใช้แพลนเนอร์ที่เลือก',
    'ticket.finalRejectionMessage': 'นี่จะเป็น การปฏิเสธขั้นสุดท้าย',
    'ticket.rejectionL3ReviewMessage': 'การปฏิเสธนี้จะถูกส่งไปให้แพลนเนอร์ทบทวน',
    'ticket.working': 'กำลังทำงาน...',
    'ticket.chooseFiles': 'เลือกไฟล์',
    'ticketManagement.title': 'รายงานความผิดปกติ',
    'ticketManagement.createTicket': 'แจ้งความผิดปกติ',
    'ticket.showing': 'กำลังแสดง',
    'ticket.criticalLevel': 'ระดับความสำคัญ *',
    'ticket.ticketClass': 'ประเภทงาน (ไม่บังคับ)',
    'ticket.atLeastOneAfterImageRequired': 'ต้องมีรูปภาพ "หลังการแก้ไข" อย่างน้อย 1 รูป',
  

  
        // Dashboard specific
    'dashboard.abnormalReport': 'แดชบอร์ดรายงานความผิดปกติ',
    'dashboard.totalTickets': 'จำนวนรายงานทั้งหมด',
    'dashboard.closedTickets': 'รายงานที่ปิดแล้ว',
    'dashboard.waitingTickets': 'รายงานที่รอการรับงาน',
    'dashboard.pendingTickets': 'รายงานที่รอดำเนินการ',
    'dashboard.totalDowntimeAvoidance': 'เวลาหยุดทำงานที่หลีกเลี่ยงได้ทั้งหมด',
    'dashboard.totalCostAvoidance': 'ต้นทุนที่หลีกเลี่ยงได้ทั้งหมด',
    'dashboard.topReporter': 'ผู้แจ้งปัญหายอดเยี่ยม',
    'dashboard.topCostSaver': 'ผู้ประหยัดต้นทุนยอดเยี่ยม',
    'dashboard.topDowntimeSaver': 'ผู้ประหยัดเวลาหยุดทำงานยอดเยี่ยม',
    'dashboard.participation': 'การมีส่วนร่วม',
    'dashboard.totalTicketsCountPerPeriod': 'จำนวนรายงานทั้งหมดต่อช่วงเวลา',
    'dashboard.totalTicketsClosedPerPeriod': 'จำนวนรายงานที่ปิดแล้วต่อช่วงเวลา',
    'dashboard.ticketsClosed': 'รายงานที่ปิดแล้ว',
    'dashboard.uniqueReporterCoverageRate': 'ผู้รายงานที่ไม่ซ้ำกันและอัตราการกระจายตัว',
    'dashboard.whoActiveArea': 'พื้นที่ที่พบปัญหา - 10 อันดับแรก',
    'dashboard.whoActivePlant': 'โรงงานที่พบปัญหา - 10 อันดับแรก',
    'dashboard.whoActiveEquipment': 'อุปกรณ์ที่พบปัญหา - 10 อันดับแรก',
    'dashboard.whoActiveUser': 'ผู้ที่แจ้งปัญหามากที่สุด 10 อันดับแรก',
    'dashboard.whenActive': 'ลักษณะการกระจายตัวของการรายงานความผิดปกติตามปฏิทิน',
    'dashboard.impactAndValue': 'ผลกระทบและคุณค่า',
    'dashboard.downtimeAvoidanceTrend': 'แนวโน้มการหลีกเลี่ยงเวลาหยุดทำงาน',
    'dashboard.downtimeAvoidanceTrendByPlant': 'แนวโน้มการหลีกเลี่ยงเวลาหยุดทำงานตามโรงงาน',
    'dashboard.downtimeAvoidanceTrendByArea': 'แนวโน้มการหลีกเลี่ยงเวลาหยุดทำงานตามพื้นที่',
    'dashboard.downtimeAvoidanceTrendByEquipment': 'แนวโน้มการหลีกเลี่ยงเวลาหยุดทำงานตามอุปกรณ์',
    'dashboard.costAvoidance': 'การหลีกเลี่ยงต้นทุน',
    'dashboard.downtimeImpactLeaderboardArea': 'จำนวนเวลาหยุดทำงานที่หลีกเลี่ยงได้ตามพื้นที่',
    'dashboard.downtimeImpactLeaderboardByPlant': 'จำนวนเวลาหยุดทำงานที่หลีกเลี่ยงได้ตามโรงงาน',
    'dashboard.downtimeImpactLeaderboardByArea': 'จำนวนเวลาหยุดทำงานที่หลีกเลี่ยงได้ตามพื้นที่',
    'dashboard.downtimeImpactLeaderboardByEquipment': 'จำนวนเวลาหยุดทำงานที่หลีกเลี่ยงได้ตามอุปกรณ์',
    'dashboard.costImpactLeaderboardArea': 'จำนวนต้นทุนที่หลีกเลี่ยงได้ตามพื้นที่',
    'dashboard.downtimeImpactLeaderboardReporter': 'จำนวนเวลาหยุดทำงานที่หลีกเลี่ยงได้ รายบุคคล - 10 อันดับแรก',
    'dashboard.costImpactLeaderboardReporter': 'จำนวนต้นทุนที่หลีกเลี่ยงได้ รายบุคคล - 10 อันดับแรก',
    'dashboard.downtimeImpactByFailureMode': 'ผลกระทบเวลาหยุดทำงานตามลักษณะปัญหา',
    'dashboard.costImpactByFailureMode': 'ผลกระทบต้นทุนตามลักษณะปัญหา',
    'dashboard.speed': 'ความเร็ว',
    'dashboard.ticketAverageResolveDuration': 'ระยะเวลาเฉลี่ยในการแก้ไขงาน/เคส',
    'dashboard.ticketAverageResolveDurationByUser': 'ระยะเวลาเฉลี่ยในการแก้ไขงาน/เคส (ตามผู้ใช้)',
    'dashboard.ontimeRateByArea': 'อัตราการทำงานตรงเวลา (ตามพื้นที่)',
    'dashboard.ontimeRateByUser': 'อัตราการทำงานตรงเวลา (ตามผู้ใช้)',
    'dashboard.filters': 'ตัวกรอง',
    'dashboard.globalFilters': 'ตัวกรองทั่วไป',
    'dashboard.timeRange': 'ช่วงเวลา',
    'dashboard.year': 'ปี',
    'dashboard.period': 'ช่วงเวลา',
    'dashboard.area': 'พื้นที่',
    'dashboard.allAreas': 'ทุกพื้นที่',
    'dashboard.thisYear': 'ปีนี้',
    'dashboard.lastYear': 'ปีที่แล้ว',
    'dashboard.thisPeriod': 'ช่วงเวลานี้',
    'dashboard.selectPeriod': 'เลือกช่วงเวลา',
    'dashboard.range': 'ช่วง',
    'dashboard.close': 'ปิด',
    'dashboard.clickToExpand': 'คลิกเพื่อขยาย →',
    'dashboard.loadingAreas': 'กำลังโหลดพื้นที่...',
    'dashboard.errorLoadingData': 'ข้อผิดพลาดในการโหลดข้อมูล:',
    'dashboard.tickets': 'รายงาน',
    'dashboard.ticketsOpened': 'รายงานที่แจ้ง',
    'dashboard.target': 'เป้าหมาย',
    'dashboard.uniqueReporters': 'ผู้รายงานที่ไม่ซ้ำกัน',
    'dashboard.coverageRate': 'อัตราการกระจายตัว (%)',
    'dashboard.hours': 'ชั่วโมง',
    'dashboard.minutes': 'นาที',
    'dashboard.hoursSaved': 'ชั่วโมงที่ประหยัดได้',
    'dashboard.costAvoided': 'ต้นทุนที่หลีกเลี่ยงได้',
    'dashboard.costPerCase': 'ต้นทุนต่อเคส (บาท/เคส)',
    'dashboard.costAvoidanceTHB': 'การหลีกเลี่ยงต้นทุน (บาท)',
    'dashboard.downtimeHours': 'ชั่วโมงหยุดทำงาน',
    'dashboard.caseCount': 'จำนวนเคส',
    'dashboard.caseCountByPU': 'จำนวนเคสตาม PU',
    'dashboard.failureModeCode': 'รหัสลักษณะปัญหา',
    'dashboard.failureModeName': 'ชื่อลักษณะปัญหา',
    'dashboard.averageResolveTime': 'เวลาการแก้ไขเฉลี่ย',
    'dashboard.ticketCount': 'จำนวนรายงาน',
    'dashboard.ontimeRate': 'อัตราการทำงานตรงเวลา',
    'dashboard.totalFinished': 'เสร็จสิ้นทั้งหมด',
    'dashboard.ontimeFinished': 'เสร็จสิ้นตรงเวลา',
    'dashboard.percentage': 'เปอร์เซ็นต์ (%)',
    'dashboard.ticketsReported': 'รายงานที่รายงาน',
    'dashboard.ticketsSaved': 'รายงานที่ประหยัดได้',
    'dashboard.noData': 'ไม่มีข้อมูล',
    'dashboard.newActivity': 'กิจกรรมใหม่',
    'dashboard.activityStopped': 'กิจกรรมหยุด',
    'dashboard.noChange': 'ไม่มีการเปลี่ยนแปลง',
    'dashboard.increase': 'เพิ่มขึ้น',
    'dashboard.decrease': 'ลดลง',
    'dashboard.less': 'น้อย',
    'dashboard.more': 'มาก',
    'dashboard.noDataAvailable': 'ไม่มีข้อมูล',
    'dashboard.clickedOn': 'คลิกที่',
    'dashboard.ticketsOnDate': 'รายงาน',
    
    // Personal KPI Comparison
    'dashboard.personalKPIComparison.title': 'เปรียบเทียบ KPI ส่วนบุคคล',
    'dashboard.personalKPIComparison.description': 'เปรียบเทียบ KPI ส่วนบุคคลของผู้ใช้ทั้งหมดพร้อมความสามารถในการกรอง',
    'dashboard.personalKPIComparison.filters': 'ตัวกรอง',
    'dashboard.personalKPIComparison.year': 'ปี',
    'dashboard.personalKPIComparison.period': 'ช่วงเวลา',
    'dashboard.personalKPIComparison.users': 'ผู้ใช้',
    'dashboard.personalKPIComparison.kpi': 'KPI',
    'dashboard.personalKPIComparison.selectYear': 'เลือกปี',
    'dashboard.personalKPIComparison.selectPeriod': 'เลือกช่วงเวลา',
    'dashboard.personalKPIComparison.selectKPI': 'เลือก KPI',
    'dashboard.personalKPIComparison.searchUsers': 'ค้นหาผู้ใช้...',
    'dashboard.personalKPIComparison.selectAll': 'เลือกทั้งหมด',
    'dashboard.personalKPIComparison.deselectAll': 'ยกเลิกการเลือก',
    'dashboard.personalKPIComparison.more': 'เพิ่มเติม',
    'dashboard.personalKPIComparison.noUsersFound': 'ไม่พบผู้ใช้',
    'dashboard.personalKPIComparison.summary': 'แสดง {userCount} จาก {totalUsers} ผู้ใช้สำหรับปี {year} P{period} - {kpi}',
    'dashboard.personalKPIComparison.totalUsers': 'ผู้ใช้ทั้งหมด',
    'dashboard.personalKPIComparison.outOf': 'จาก {total}',
    'dashboard.personalKPIComparison.average': 'ค่าเฉลี่ย',
    'dashboard.personalKPIComparison.averageDescription': 'ค่าเฉลี่ยของผู้ใช้ที่เลือก',
    'dashboard.personalKPIComparison.highest': 'สูงสุด',
    'dashboard.personalKPIComparison.highestDescription': 'ค่าสูงสุดในผู้ใช้ที่เลือก',
    'dashboard.personalKPIComparison.lowest': 'ต่ำสุด',
    'dashboard.personalKPIComparison.lowestDescription': 'ค่าต่ำสุดในผู้ใช้ที่เลือก',
    'dashboard.personalKPIComparison.dateRange': 'ช่วงวันที่',
    'dashboard.personalKPIComparison.dateRangeDescription': 'ช่วงเวลา {period} ของปี {year}: {startDate} ถึง {endDate}',
    'dashboard.personalKPIComparison.errorLoadingChart': 'เกิดข้อผิดพลาดในการโหลดข้อมูลแผนภูมิ',
    'dashboard.personalKPIComparison.noDataDescription': 'ไม่มีข้อมูลสำหรับตัวกรองที่เลือก',
    'dashboard.personalKPIComparison.errorFetchingData': 'ไม่สามารถดึงข้อมูลการเปรียบเทียบ KPI ได้',
    
    // KPI Names
    'dashboard.personalKPIComparison.ticketCountCreated': 'จำนวนรายงาน (สร้าง)',
    'dashboard.personalKPIComparison.ticketCountClosed': 'จำนวนรายงาน (ปิด)',
    'dashboard.personalKPIComparison.downtimeSavedCreated': 'เวลาหยุดทำงานที่หลีกเลี่ยงได้ (สร้าง)',
    'dashboard.personalKPIComparison.downtimeSavedAssigned': 'เวลาหยุดทำงานที่หลีกเลี่ยงได้ (รับผิดชอบ)',
    'dashboard.personalKPIComparison.costSavedCreated': 'ต้นทุนที่หลีกเลี่ยงได้ (สร้าง)',
    'dashboard.personalKPIComparison.costSavedAssigned': 'ต้นทุนที่หลีกเลี่ยงได้ (รับผิดชอบ)',
    'dashboard.personalKPIComparison.ontimePercentage': 'เปอร์เซ็นต์การส่งตรงเวลา',
    'dashboard.personalKPIComparison.avgResolutionHours': 'เวลาเฉลี่ยในการแก้ไข (ชั่วโมง)',
    
    // Filter Mode and Navigation
    'dashboard.personalKPIComparison.filterMode': 'โหมดตัวกรอง',
    'dashboard.personalKPIComparison.navigation': 'การนำทางด่วน',
    'dashboard.personalKPIComparison.previous': 'ก่อนหน้า',
    'dashboard.personalKPIComparison.next': 'ถัดไป',
    'dashboard.personalKPIComparison.yearSummary': 'แสดง {userCount} จาก {totalUsers} ผู้ใช้สำหรับปี {year} - {kpi}',
    'dashboard.personalKPIComparison.periodSummary': 'แสดง {userCount} จาก {totalUsers} ผู้ใช้สำหรับปี {year} P{period} - {kpi}',
    'dashboard.personalKPIComparison.yearRangeDescription': 'ปีบริษัท {year}: {startDate} ถึง {endDate}',
    'dashboard.personalKPIComparison.periodRangeDescription': 'ช่วงเวลา {period} ของปี {year}: {startDate} ถึง {endDate}',
    'dashboard.personalKPIComparison.noDataAvailable': 'ไม่มีข้อมูล',
    'dashboard.personalKPIComparison.export': 'ส่งออก',
    'dashboard.personalKPIComparison.department': 'แผนก',
    'dashboard.personalKPIComparison.selectDepartments': 'เลือกแผนก',
    'dashboard.personalKPIComparison.allDepartments': 'ทุกแผนก',
    'dashboard.personalKPIComparison.noDepartmentsFound': 'ไม่พบแผนก',
    
    // Department User KPI Dashboard
    'dashboard.departmentUserKPI.title': 'แดชบอร์ด KPI ผู้ใช้ตามแผนก',
    'dashboard.departmentUserKPI.description': 'ดูผลงานตลอดปีของผู้ใช้ทั้งหมดในแผนก',
    'dashboard.departmentUserKPI.filters': 'ตัวกรอง',
    'dashboard.departmentUserKPI.selectDepartment': 'เลือกแผนก',
    'dashboard.departmentUserKPI.selectYear': 'ปี',
    'dashboard.departmentUserKPI.kpiType': 'ประเภท KPI',
    'dashboard.departmentUserKPI.ticketsCreated': 'รายงานที่สร้าง (Report)',
    'dashboard.departmentUserKPI.ticketsAssigned': 'รายงานที่รับผิดชอบ (Fix)',
    'dashboard.departmentUserKPI.noData': 'ไม่พบผู้ใช้ในแผนกที่เลือก',
    'dashboard.departmentUserKPI.noSelection': 'กรุณาเลือกแผนกเพื่อดู KPI',
    'dashboard.departmentUserKPI.selectDepartmentToView': 'กรุณาเลือกแผนกเพื่อดูผลงานผู้ใช้',
    'dashboard.departmentUserKPI.noUsersInDepartment': 'ไม่พบผู้ใช้ในแผนกที่เลือก',
    'dashboard.departmentUserKPI.totalTickets': 'รายงานทั้งหมด',
    'dashboard.departmentUserKPI.avgPerPeriod': 'เฉลี่ยต่อช่วงเวลา',
    'dashboard.departmentUserKPI.targetAchievement': 'การบรรลุเป้าหมาย',
    'dashboard.departmentUserKPI.users': 'ผู้ใช้',
    'dashboard.departmentUserKPI.userPerformance': 'ผลงานผู้ใช้',
    'dashboard.departmentUserKPI.department': 'แผนก',
    'dashboard.departmentUserKPI.deptCode': 'รหัสแผนก',
    'dashboard.departmentUserKPI.activeUsers': 'ผู้ใช้ที่ใช้งาน',
    'dashboard.departmentUserKPI.year': 'ปี',
    'dashboard.departmentUserKPI.companyYear': 'ปีบริษัท',
    'dashboard.departmentUserKPI.totalCreated': 'สร้างทั้งหมด',
    'dashboard.departmentUserKPI.totalAssigned': 'รับผิดชอบทั้งหมด',
    'dashboard.departmentUserKPI.avgPerUser': 'เฉลี่ยต่อผู้ใช้',
    'dashboard.departmentUserKPI.target': 'เป้าหมาย',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Get language from localStorage or default to 'en'
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'en';
  });

  useEffect(() => {
    // Save language to localStorage
    localStorage.setItem('language', language);
    
    // Set document language
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = useCallback((key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(`{${paramKey}}`, String(paramValue));
      });
    }
    
    return translation;
  }, [language]);

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
