name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

permissions:
  contents: read
  packages: write
  # security-events: write  # uncomment later if you upload SARIF

jobs:
  build-frontend:
    name: Build & Push (frontend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/frontend:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-backend:
    name: Build & Push (backend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/backend:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
