name: rollback-prod
on:
    workflow_dispatch:
        inputs:
            sha:
                description: "Git commit SHA to roll back to"
                required: true

env:
    HOST: ${{ secrets.DEPLOY_HOST }}
    USER: ${{ secrets.DEPLOY_USER }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        -   name: Deploy via SSH (rollback)
            uses: appleboy/ssh-action@v1.2.0
            with:
                host: ${{ env.HOST }}
                username: ${{ env.USER }}
                key: ${{ secrets.DEPLOY_SSH_KEY }}
                script: |
                    set -e
                    cd /opt/hello-cicd/prod
                    export REPO_OWNER="${{ github.repository_owner }}"
                    export IMAGE_SHA="${{ inputs.sha }}"
                    ./deploy_prod.sh